{
  "containerPort": 8080,
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:347077c2e34c67badac272c0f2cbafa7ea69dc2cccc6661e59169aa29d55e4ea",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/30"
  },
  "iris": {
    "deploymentId": 101,
    "serviceName": "strategy-e2e",
    "targetName": "aws"
  },
  "release": {
    "id": 45,
    "sourceSha": "446917d6b46febbe2b4f7927166a0cc501de667e"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "strategy-e2e-30.likelion.uk"
  }
}
