{
  "database": {
    "engine": "mongodb",
    "image": "docker.io/library/mongo:7@sha256:1f995ad6fdb93244a1addab1b58f934a0bc2f5643c38e02f5e9d7f0c7d227a7b",
    "initScripts": [
      {
        "content": "// Executed only when an empty MongoDB volume is initialized.\nconst appDb = db.getSiblingDB('archlog');\nappDb.createUser({user: 'archlog', pwd: process.env.MONGO_APP_PASSWORD, roles: [{role: 'readWrite', db: 'archlog'}]});\n",
        "name": "00-mongo-init.js"
      }
    ],
    "port": 27017,
    "storage": "5Gi"
  },
  "iris": {
    "deploymentId": 138,
    "serviceName": "mongo",
    "targetName": "aws"
  },
  "projectId": "20",
  "release": {
    "id": 71
  },
  "replicas": 1,
  "variables": {
    "encryptedData": {
      "MONGO_APP_PASSWORD": "AgADHS/JOgBqSMu/ld5elrb+jSfcJgQ8juz5/wpiJkbMoNpjH8VrSAdQtoVFdOA554bn3jofiMUsjxCNmpqT7IfoHZMgDnuDETK0QKbLkWwuWURav1WPtZsAwW2GBkh2vVhobZmg7swTXO7+aAQUZHkqP0NBrxOd1Ir6+bAdyB+FvyfXy7o7hMcGJDj1wSlePors7vyC8E9jFFhdfTUEZQgPyY/F+OuQtZn0KVTa43y6anFHO/EzAo9BzqoiaV4ktGopBah32z8aQ0VSZ0FbF/tc7ruj3sCC3fLryeG6xLCgY0EXa8ANUAvTp+3Xj08HlrsNuxuNUEAzTOrEpg9xDrQvikLE+3qsJVD5bXRCOtaoe23LhOD/7Ud+GdiXjTVwlTedGdgkynTaL2xKxTeXqjoruEVBrvPbOM3EMBMA1XSf9vJRNu0Q0m/9geQkhosZSs3I9phvRBHwCzfOzv5ZOIz7H/kfZKIPkiPhoYUxYmko/k5ZftQSwcH7hz3ie8xrQ8vwVYf9eH0VlLGNbY0hR2iaLWpseRi++16J4UT1oJGi7+sfA9VVXpSf7vY/Y5N7hOqDpnysAbJQRGVi89pW2rQeH0QVEBfIpSoK5IdKFnw1yYD8edq9ng9HHenYnHdtE5ASo+F7mURBX5rzla6ex8LclM1E/1I0BnkS6pcKCXI21m3iIU0VWc3cvDSJsKoJcLgFqkkGBMHLPBBNgKKCcbDtco1Ih5ndUM6s+RQ+R5Vex4/BXNnLQMqDdiyA",
      "MONGO_INITDB_DATABASE": "AgCJnt0DBheSGFdTYotCEed+iNW83YXeCzc6puJ07Of5QDsgPsDzW/wqIx8BB0hE461X9r7WVesRusbdPjLSSSGL0A49cICxEDt/6M20yFR2cMynblRbF+CTRZX8amyh3ZopHDiAtiHuz184172rga9PS81OoP/PEz9yEu/G5O66KVltw5M2V6MsZ+KAwM9ARufa5NNq18aFrZ66YPZ3xg9SueEcI1z/vq+SsBqhEqkrx4iUYzWVqkV/aSKuT74JTx02t3HNG3wrDRgTeH0UqcnBp8qyhZzmALl0IZuGSYAGSYcif+qeECwhlWJRueBRVLn4QqmL/W1nusktPpIBkA0cdY+qlcGojLHcw+50cdPVyfMFlbI9c+um78O1n5ghcmaQ1f4mpS7IPrnO1ZGElIBlsenM7CdADxmLKKCNNXfLQuuC4m340FJOD3+JhRJ0mBKJGhXqNX6GHgtbXsqn9ISbKL/j17wd8o4H7nI9UVl3Wy+g+YnjDFbQP6UCoxvNQ8uIXbWUHGe4LAhv2DdECB/G+sOS445HJrjC5PDvVTDVeX8dQ2UscV3RpYe2XTXuvArcXNGnxEQJVoEEjk/6ZpU75CB/iV+P5pdZshWoYLHZSNM44p0eLW7zUcQ6YgHZJpmJHivwPvQHdcEJHR/wxU3bstxZhB8Ae5kA8Rt8d4nQ+Ei+TnC5Fzm9D4oZUYKoDmvSy3CKbCOf",
      "MONGO_INITDB_ROOT_PASSWORD": "AgBHXRCSvBP5DOM0IFzh479nhoqLnF5agTMLa5Dw2MOcDqKqycu3Ew5uh63+9+6oUkYUtJqPnJix2TicZQh0KMtEaXWuagCnEZxWIWrQEAjV+TVKQ8rK/vqrppL8sSzcz4T4/TGD3QEnKHNKKCOSOi8+K55jNAo144jN2B0ONFxSLuuh225F1zja7OPjld0YqoIKqZAjPabOK/aPBVy9xGKhYtDOioY3sGhjpyjRxhFq0OI0GcWS0jhFXoAu8FwOR9fhEC0DDrgNzPkgYZD6mzGDSC5wdd5pPRDSKeBwcdFVBXidO/6cZed8XUpJImFdYiIE0UISIN4GHqBx0zxw4rFYe7EhytLyVTZw0/2Ek2gTo9l6tr7tdKdBGOZfsgFVo4i75n0r+C0ANzo3u3rtSlXOK6VsBMX2Ny9fwuXUIA05eCqjrRwX9vCizDyWThSfFnlw0kshH5kJtTRuGgJK641JQ9dVIu67wVLgrvbxHfwpsFwsSJpUNioUK3cjv23Tb+7N0j3X845O8yDCe13d11kpJaOADYKfeFmKy91XPIv9/pHfpO5q75qCgWv1WqktELXuKwBD66rYs5uDU0VBHxmkwC7omdlI/FWoGLgZHkRIbafGas+87rROapVAQZ7s/25CpHbExQxOBpE40MJeP5vejXEtO5ZEpGRkvMfs54M0hUmqTFuVxGTvGQ5/2H5B6417S0HUT8tMuMPhHPttX5gnZ0i1lhR+KE7sOwNC5LprUw==",
      "MONGO_INITDB_ROOT_USERNAME": "AgBvMPUKxHUJ7WRAADxSAg4QdSPa68fOZiYK0ew3N2sMiej4D2RXRjUZAPlRVvbHTX8WrAZPmXXVTNd1tEYxDMOOcpJobmkodljiwXMtfWsSd4TaoqwhkwZ1sLaHcfiJOPmMk1vD54ho1BbdzDa6pBkXy5F9JPuQ2F6TdiYaeqOw3HGdGL60m2zcfQN5QXD05+jJgosRAQebq/K/AzPGhogYCA86P3rt5bjilNMD53ed+4VVLSdnHKFYfUVRsTVcNu3pSIwELCQfpSV3tkS+UC+3t+Ghjb+IFKQ7s9o+maZaWK45hNqmpVxRVPyXNyDqatVhUX6+kPZ2AF/CQULpY+/yW3AypNMYtAZZGE1I724hAkpxMw0zvPamz7jPj2COAXBLKDQPhrgsjNpcKL1pp2u2eP9ysWVJoCmejQe/Mwi35KKwuN3MwZtqaR9dZkUxrcJrykq0MVlo6TKLfaJE5J8aWf0Ma/TLJ9TLNkRIAYv5yPDCtF5Dt4+I24kXEBD1Vs0SioH/fke9xkAJqCpoBRcRviLU+giRgs22VloPiLjFh8wVYVceZ4odOdn+lOLmWoX1pK5PCQ0REDi9RZVeml++NDpVfDvuKJ0uVLhVxJpMp6djk4hgqa3lXehvQf/dqOObZOgZER/l7RmG8NGMxnjkEGEQ2p8fWRi/wkQomCUeloV2TmKg7aDXXUe5s+URENzYSqo="
    },
    "name": "vars-r71"
  },
  "workload": {
    "kind": "database"
  }
}
