{
  "containerPort": 80,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "hostAliases": [
    {
      "name": "api",
      "target": "app.svc-65.svc.cluster.local"
    }
  ],
  "image": {
    "digest": "sha256:1c562dd1c614b510b5539f0a4959b8222a662331b28d347860470cc8246df43b",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/66"
  },
  "iris": {
    "deploymentId": 222,
    "serviceName": "web",
    "targetName": "aws"
  },
  "projectId": "37",
  "release": {
    "id": 108,
    "sourceSha": "ad7ef4001b734afd4e1a1213c29a6c6e939097ed"
  },
  "replicas": 2,
  "resources": {
    "limits": {
      "cpu": "500m",
      "memory": "256Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "128Mi"
    }
  },
  "route": {
    "host": "web-66.likelion.uk"
  },
  "service": {
    "exposeContainerPort": true
  }
}
