{
  "containerPort": 80,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "hostAliases": [
    {
      "name": "api",
      "target": "app.svc-65.svc.cluster.local"
    }
  ],
  "image": {
    "digest": "sha256:00f7f4ee9af59eb84e2368452aef9168f5fe15acdcba8783f1b7de39cbbae8b3",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/66"
  },
  "iris": {
    "deploymentId": 230,
    "serviceName": "web",
    "targetName": "aws"
  },
  "projectId": "37",
  "release": {
    "id": 113,
    "sourceSha": "0d699d154c44c8cb7395d3492234c717faf0008f"
  },
  "replicas": 2,
  "resources": {
    "limits": {
      "cpu": "500m",
      "memory": "256Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "128Mi"
    }
  },
  "route": {
    "host": "web-66.likelion.uk"
  },
  "service": {
    "exposeContainerPort": true
  }
}
