{
  "containerPort": 8080,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:730b8e9a97128cb94bd1637d461506a9d317987a558037ef59361b9f75f5dafc",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/56"
  },
  "iris": {
    "deploymentId": 171,
    "serviceName": "railway-deploy-demo",
    "targetName": "aws"
  },
  "projectId": "30",
  "release": {
    "id": 87,
    "sourceSha": "446917d6b46febbe2b4f7927166a0cc501de667e"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "railway-deploy-demo-56.likelion.uk"
  },
  "service": {
    "exposeContainerPort": true
  }
}
