{
  "containerPort": 8080,
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:f0c66a67e521bd5994f46ba42392c8f5ccc72013bf4f0d3bf1017780b3b08f3f",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/57"
  },
  "iris": {
    "deploymentId": 184,
    "serviceName": "railway-deploy-demo",
    "targetName": "onprem"
  },
  "release": {
    "id": 95,
    "sourceSha": "446917d6b46febbe2b4f7927166a0cc501de667e"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "railway-deploy-demo-57.internal.likelion.uk"
  }
}
