{
  "database": {
    "engine": "mongodb",
    "image": "docker.io/library/mongo:7@sha256:1f995ad6fdb93244a1addab1b58f934a0bc2f5643c38e02f5e9d7f0c7d227a7b",
    "port": 27017,
    "storage": "1Gi"
  },
  "iris": {
    "deploymentId": 129,
    "serviceName": "mongodb",
    "targetName": "aws"
  },
  "projectId": "9",
  "release": {
    "id": 65
  },
  "replicas": 1,
  "variables": {
    "encryptedData": {
      "MONGO_INITDB_DATABASE": "AgBuDJFTgLxKQiT38vPzsC5JfHvip/uzuO5ZrSuff/bwbqaXdqcBf+hPpoUOTUU/KZlK7UgkmC/mdTK/HPO76edc99dmlX5JaeQiu9qcKX2oFN6ZWCB9FL/RZixFQOUM+9KWy0bzqiDRbhtbia9Ev+Gch03k2Nd6n7wPtLdpOILNRMLbxZmDxkjp2Pl9Knk8C1CfLXbKtu1zZRfO3+8GGx00ZuMqVqWTUVJCmVcxz0yIQt68952rxOQuG0CrQeJbHn7KxzdJ3mvNj5U+b/XX2ONizTEbJKWDj7uJOHE/eSuhFZdOeQd8OLIUUv53F+MNfC6O8yMU+Bbulj3saAvH21BhJgVnlZ0c0rtYe5p3ASBTJCGvxumyNQtpL7t1tLW5zkgq3CqLUfhAQWGJGVVNfUjEJWclOPojBUy9JL4rwUlyXpQEw80YfpOHp3QqwXU+t4ZG5bUJXSBK1YFbrcJrtyJqaw75ClUR/cXZj9g880Z5EIsW146waAndSmXmNmfpqzVH0ST8XA8rg/kx33rJeAKePlbE/8CBljuc1tmj2kBJlumfmdqPNobNDqgUFn6MnL153iEYrQErAMtBSEiib0w/yevbiG4fMosCMohXMWY2V4lquUmsOfm7szQLXFVDb+4PtPAS+s5x18KDqBEt7ozZCaNsTYSgpWDLyr537C+g/p1d4eMF8ytIosKgNKZ6rTClasI=",
      "MONGO_INITDB_ROOT_PASSWORD": "AgCk2PYDJBjsJpzso+RsFuMij+69iFa4UjrenWVa1mdw+ETeoWKBz7dfbAYIq6d/gi1hhjycc09gINcIlJbcjXx75ra4xbex83i3JZHfTBVb2DC7zSgDVuEXqBzOmihw7XQqpZJ4Q3SUv6HwLibW5QDaeVt221I0r+0uflYdSAtp0CM5K9nRGQEybmr36/yySLtmxN+/IadCAbewQGeSGtmOTctxy3QvBFTbVfX8/q6kL+RfVHNcCfRcWAO69IJUGnmqc+Dl5rWYMmfq9+iRbDKtHeMRM27iUhZgOmc2CthhgUnDDkfMOqkzN9tc6RGqe08PiIYG+CTXT2Db7mfEZdwo/aWrjBjLD3YtE2IHcYrVQ3Xp4jh1Ffhkc/1omTHAFB9UDq/fLPLIUddT3AuUP66zX3fQrVLSXjEr+K13T3pRvQ1dy4Wet2nhu+4BAdPuyCPUoNmuinOju/TJLoyhd1DW/6piXvsrYyP+pZO3goKqNIb7/3sdcc5toZshEGVOC09dVN+z5AQqijl6PH2PWUMkoXa460lXRqcAX10Ay2n2LXG6mO1zQTdr5Rr/pBs9hkjL8E2fP7UquE9k3V1dz5Zkv4yaZ1WuPlvlFcAMnuuhwytiQRADSgNSO8n720V7n7BI758SVZgbCAWBDFTkDCie9HUl6NBKALVkJS1TOt8VYM0EC5tomnlF60W9kbburZajFsDiUtd3PMvSiqRzKtiqCEciKy8PdzmMf8VirTWSKg==",
      "MONGO_INITDB_ROOT_USERNAME": "AgAla4ujKVzGkM87ZJKMdCMMrm2bJY6UrLbdTibRnU6Erg5CjzEFb0YywtPvYXqzsJ1U+txlA46Zdub5yRZrWDFTPzLTTp1qC1zShY4uH2h/bMkTvmwQY0i7Vn2DsWhZ3kHnhiSC3b/Vdil+P5y6Ym9ZiP1TNxQdV69nybm/INEB1TlQng7tbAzr4itOn2LaJFZBAb+lxDDzFviWk0aPnBY2pc01YCmOBpUmbKqZJYyZzeITxG6g/F0NHDzK/55ceDx5aX70JWarmGr7OcJpzFTy7tjPcGcVJ4oE9rfjp1dQiibOy9t3ZOId21a4PX4kMpuUenkD1Ism4QGE2dnUA4wiYyRxJ1ZYYJbssGRA3V7XY4D0jDAcgTeLE45UpSe/UQDnjCAm21lGQT80aIMtfmJkWCd4lVSzOj7ytA+w38M7qi1Upt55ltfW2/Sl+jK5hr1Wi8j4xCDTRCkKXPTmmWwbjcxIkRfLFqi6qcGUAhxNVzq5MZ22B84AdplNpxNYGUQjpGn0BEuvysRQhmSDVYKGsk8PNyN2j0s5w31UaSK9yCpH9EpjXBgXUs5kysIEIP22PghdoVweLGLo356yTznS4OpEMEbE5R7TWEzbIYLRAXmxULFkjf8oUVd4xx8icjdsXUCuKiX9dqIs3fqZTmL11KCbY8NscledkY49ArIioRMILaC64U1SD6ecRO4MdgReJzA="
    },
    "name": "vars-r65"
  },
  "workload": {
    "kind": "database"
  }
}
