{
  "database": {
    "engine": "mongodb",
    "image": "docker.io/library/mongo:7@sha256:1f995ad6fdb93244a1addab1b58f934a0bc2f5643c38e02f5e9d7f0c7d227a7b",
    "initScripts": [
      {
        "content": "// Executed only when an empty MongoDB volume is initialized.\nconst appDb = db.getSiblingDB('archlog');\nappDb.createUser({user: 'archlog', pwd: process.env.MONGO_APP_PASSWORD, roles: [{role: 'readWrite', db: 'archlog'}]});\n",
        "name": "00-mongo-init.js"
      }
    ],
    "port": 27017,
    "storage": "5Gi"
  },
  "iris": {
    "deploymentId": 185,
    "serviceName": "mongo",
    "targetName": "aws"
  },
  "projectId": "29",
  "release": {
    "id": 94
  },
  "replicas": 1,
  "variables": {
    "encryptedData": {
      "MONGO_APP_PASSWORD": "AgBxxqPkAaf1rlrt32tQk7+zz332O/hOyFhiq7HeFucuwEtfWqEu+xwX0PlIJd0Ut27qZsInXrwZafgh1D77HYTo2fDWGkXxrDQSGVK9iIa22s9JUsudxpP4JkOP4r2jmYnZGenQyRi2e4zpRyTw+VGjKtJeZ6JY04H0n/ZUFRGNVgrVRawr1nt5Nc4EPcEg6BIPiy9fuBT7pVVzRQPMEaoIvVu6VjpLCqfWpOFQtjJd1b7+Exx0Q4EjEDF5g4V3qV6+pUndp3y6OfeEpaZaT0C1dtruauOFidTp7NgbKWmdTqYUsqq3kRqC2Mx2Fq23TU8Tt0eYl9zrgtJ5RJ4EE5xxjFIgAY+tGy+0Qx2BtZxodCHthHW0Fnqhiqj4PE2JmIT9o0LRWWub4LaC+LCN3+DCqIU7HP30gQPX2m29e8LTowbzpBG/X49vhgIKUDR6CkX/pzcuWNC9oaO8oKjTHi3dvsUD+tUcxTU4Ql5YEcsoWOfD6CdLk0INPtpfChIcAczzcnZb37u7fkcUgP2eSOtu2pLzA5q2IYhN1/xNK6MRuqpbsKv5cx421ZOMjuQXLgVyTx0y/BWxkXBgG82qHYQK/T6nx4C8fmoxUuzpKlFHWLuiRFmEKCNSxsXLrWFkGXUZELQ4LtoqKL4oSMTT9JaoR2tbDNNVBSfcs4jSfWbODcfYhYb+tEl4L98+WfKoLLqUcGpFudAdrbgM1I4bY/fY2A2fk9KdbDuhBpZ1OkRUE7ouupNRWvhbMYI3cV2PahdHhxVzrbYzOVBtyagv4arc",
      "MONGO_INITDB_DATABASE": "AgCpCcYq9IcqtmYYpj6rrc6UdCudKgNcF2fuws0CI7DsURY9TYiBH8L4AkawbhMMoIY3kDRWpTAP9ZhEoXsqQd0q57MWJtoIXDltNulz7j2c8grfa22RpYQRdFHrr0eU+ieTo9lTdJrBUTgny5HlRFeETMwZ76o4M4uncDHC6PSpWxyN+SQLBpFXRn/bqcFxcDSie5cbhql99jWZ6g99zDSsObsTZCEzWguqNx4voQRh7Awpk5xvWPzPdEscsfNWZFQETLSqCDxcLSEbMKtXgo/xjzcoeRvgQczER1CLK6UPz73yYpPWGGr+k6mTsqS4A3qvQdNqOg9qGdWxhViEVjemDEvoTFdBh4OB8DO9qsNXH4CRwp52PQCcj6Cv8Sn/XT+qeQ3TL3zutXcuvfCoyRPV1N7T78RykR77ZPYrf/u2TKq8/wjULHFo7E4mnpJs4g339tc4GaBpmCNJhGM+7I43BGPsawOkciQmqF1I4XGqrTrvj0xbniOdwcARWPnZ4wlcOIDqDsaNH1sMwA/az+sS/WNouc4MM2MSNme1MlRfSAaiCVknOaTe8BrYS0/afaK9B7k7A7AQNVp3OCiQzqlanxZDETBfhI13okS87nJyrqKJggG87x3ZNiH63+l8T/+qGeqMQnIq5LfpYyvucrxBqUeIT584OxaMfUZKoz+d/OgyYFnqI7CiolpW7xdAV88SABhbkV8B",
      "MONGO_INITDB_ROOT_PASSWORD": "AgCKs5wPFglWttdGDtpPWdMVDkRfHXBP8cr0yU28afX4KuAkNVpF7LnH9NACCl3LSOOTwXTS7J9NU1ll4godu6hGic+Faz6LGxpSnrM+6mRjpTa9ZuUA4oPq9U1kHA5YPglbtLRe6+/0qtfYYj5C1WEYY36+rz0vpuxSItLsO1kGofkhm5sQKFMBjCm0gW0jd2zy/bd5zTFAxHl8ytBvLFjmL8jKbbsrXVqx/i3zq6BIj8DBMKUqbiM2HoycNwgku3CibpfaoYm7X4B/jQ1x3rSH2+ThI5jgfzXYeX67R+et2IME/twR/ifO7LFC1rmLB10U/djKLZeRX0gJtazUmDn7vSjfFOQ5sRs97jYBwlOLSrT2jjv8nT8VzBWdEat3w/zeyrvlkcJoylHZ7nGhA84oUxFDbemgg6xGKAw6gQIRNfQ4dFmod5uVHAcRt7kPscLhnVDElBxTr1DNIe/C8hA/W9TV2IuSK3RbIzwR3n4VJOHO+VAv5L+ZoJD7GnONwliR/KtkR3ZZWjLR1VNHqp2LPuiL66s5azSB9UgEPhCZoCyBKsWCBrSc2K2t7ZWvDyzZu3z6VJgbnAzE2t7zaehrpVtnfOeGVOwKdFAVLSyMGEeSPWd8PGzy9wdufeJGbtcG8f9JzBZrQ3duQprDewDYDZL3HiEzXXFkiLSc/E+RbQQ8cmtpfkfB1ANKCS5Cd+q+qhmCKwrxHMYyg0bU5FcplENKK0/0jqeVIVZ6asanwA==",
      "MONGO_INITDB_ROOT_USERNAME": "AgAJZIO31yh7vpDvugCLMdhdpvSmd9ZDOXZWrgv9vEurgGQGqaPW7aNl7uZeGPuLrCJBTGVbJaGTHJVe5OYVCG/qRG9v2kcdGY4FeOAuLqUxY8lRIZyX6x62Yr2YfaJsTINlOd8D+R5Yd+odo7n93BbXaWsqPuNk58V6Zp1ZmLAM+SymWCxI9Ah2DItWt9+X3xcorf/VkGIzIoxEucAeCknRBPIg8M196gubiCZXZGochKa0U8NaktyUTSp6MnD8Pf9tjLNtqMasH4Ruwr8UQlMp99ooaR97nRJSR7tfxk7CPOy2wjS2z48srriEyBx2lpC65Ve7mRFh4VwfeuGJsbSPQPNxkV6EzqwGyUBXSXpMYNwKMSHm4NSZrUB3fU5U0Rs+JAu6oVTBP0Zx+XZ1KvzdZg5v1XAuyCb08k1aKrx2Q9sQhkD6FFzl6Ki7/aEgvU841tZbAUVJg64yepRk/j6y7EWuKOmD4vLOeXlE966Ggi4W7+2gVdywqyVoYtXgq2j9x/rIxPsslE3HdljcygYKv1s/M1hSykREuDxk1C/FGRS6s+r1k9y7ccHz5YZgWJZboGHBrZIgzUsZwB1IqtM9JUvT6LzgtEm4/XBGMlqbuL3xOzBrl/yZfsNdz8+EoYdsxZBlt2ZmAXibVeeiKTl5IuFjRKwDAC4VeBzTnTl6hg+ehQNDHZWuzPxZc8C9xE0KRO8="
    },
    "name": "vars-r94"
  },
  "workload": {
    "kind": "database"
  }
}
