{
  "database": {
    "engine": "postgres",
    "image": "docker.io/library/postgres:16-alpine@sha256:721873c34ceb9f8d8fc265984940dc982404c105f19ad51be9fdc5970a6080ea",
    "port": 5432,
    "storage": "5Gi"
  },
  "iris": {
    "deploymentId": 234,
    "serviceName": "db",
    "targetName": "aws"
  },
  "projectId": "45",
  "release": {
    "id": 114
  },
  "replicas": 1,
  "variables": {
    "encryptedData": {
      "POSTGRES_DB": "AgBpfDBt5BQo9UZDo7i1LEOIDwfgHQCsIxV+YXGG1BuAjDF0Q2X7kBLfm/t7iXMZON8hmWd/ICrQlwPUVTP+y2swU69TJKvEuI1TNBFg9XNxoV0mib/xIvnE4J/X0DIw4sk5xbV/qfBMVv1rqmNtpdVAaz/2jssCP8HIRKJXOOImVrPfol102yhouDVV/GxwwSutb9QnTYnURrIBeBa2kG9EskjLjG1ReOfY6/43/ylludGAYZeUk8/gy+dn/l4HC7DY65f3U1Dsq5cHFXfYy4VPLhcota4TdS2nxE48v1WOa5NB+C7FUGZWrd1z0vfDRaZV61jFc8IOzRBi1/quDmJFE1Nt+drw/8xAdmdRHdLSyBmGvXWeibB5dn9dFzzetqtJKx692MKHdnQfYe0wpRMWhOiS5TJQmlwUKUMSpYT4uIRnYBzSO/77OmkxMGogQ95I6X/DTChzM0KjNGWg6qEeF7yt4+Pc9c2uZkM5wsY7ZzaOXvqF5vBXvkgQxQGgurSMoXUTr1q1vumP0ZbqPgUK0Kki3w5hsdjwH0oSpU7JRs+qkeIHOpeZWFsTtpMuWbSXXXV0C3jinVIIq+s7I4t3QXwO9WxF28D0KmG01LFU5F1/N8sRhljjJpH/4o4c4iYMGD46tc+q2eHMmA+PQjKT5o1V1NrmpfE6I8fmW9secAL2sF/hRZ9k1QZa7Sd8GLIhgPWI",
      "POSTGRES_PASSWORD": "AgCZMrU8bHkbRYajaXNpPrEkGQU1WuexWOrAIASb2jAFWwmZBJLSOFC/4GngZzf/Us7ZCd44m0EjVgUlWqeMTYlkwqMuOWb528fyL9rELdxR12A1OlJ3siKrd9nBopJxjiIhFbwWbYlOJAcuLWFtkkDGGG2Yf9+hcwieTxEkuPr8fWyrl+I9ioI+D75ds7wwYL5X5SVt7qHHfFmICG46HsYMMvQBQ2Yp6SdBTqUwL+O9oSGcL+FzXXWeC0cW2pqrEMMYjGnORVQ1hre3dCb6N3ueRrIQ+HL6sQaU33fHpXg55RnSCyCrCIfLJrF9nvswRCa9l9csKFeW9FxlQhSA3jjkaxwHvH29ysrw8zDGmkGjTi56jBG+YgJBlCxRA9Yv6k2K8jd1XANSaqWPKiGEbZcoRGQKk/v3CRLl48YhVcFgSoUJJYWT7ZqpLuliIALxd/VkMHQCYNEcHY2BUDVbCFn7CNKC6UvKqzNRAJQgnWjszNJ+HMG2q10j18DYvKZwjxMYRxWyID0f0hHPWB7EAc4yWOX9v2mPQ3sZG7fsPr6CXnnvmy6XMUB2iU4gVrEl6F+ypkgb8vtHgXLjmhWMwUKbZI0izrbKc6yfoqN48uo5dEX0S8QyevyhH+M2ZsLE6BGzCAjdiw+D9oK4izLejDEyxQkboiNwP1490Vn6bM3DaLWvIQIWxVD9mmba6qxYIEI6VSt4WTBYMBbqxEbDAw0jVrEuNzPtMa3Mex7W1dZszw==",
      "POSTGRES_USER": "AgCdTUFvpkwIVZJlyYopzRha8vy4jB8CG0MLU37OVC39yOEVvQ6ByyyabwgJE/JOE0bHMlamzyOVpb3WgqRslgwGNTPi84IsXz4gebBnKx7llpZ5HNSodxgdrusUT8D2B55ij613WOjAp05/CaXFAZaVt8fxQelVWaJJ5Ib7CaEL4t1od0MzaMNR0Q49CHF2JBBFK0ThT+0wy9G/bjtius1Jdhf5hgSWcDwaAr/olnBhjWPUiU52Sk4UVJPZaUkcpLnwCbhkSWHk94g6xHPg7976G95QRPfbf2iN1K0RH5syCCc1APX7bwkJKQPd4/p8VPFLI7W1rgbqf2540Ot1ko1ADLh8obRpGNkMOCoztoXYhSLN8VlyCmSaRcdhPf6id3GdATQ/8Q9luyR+rKcw2LA/fYczQ8W+Cqq7+EIEYXe2/EA0Ugwu+WzDTQRFfuBYGfOyxRJJUZBHU59MQ4D0mg8SEZUzPewWnzZtRZ8ueteIlEyJZpOE9kdAz+GeSI7uddVjnFZHeePzu+A8An6TNq42pBb1bg89ZLhEMfTwXlpPplQwehvy4aIjCICxEk1KMR3YH8Ti9RNUuUBRoQyckZ+IUXWOUcmUDCPgkYRLswzfXdV4k9Nndxu9uJW5QnXphbO7lYCOmp6fbxiK1eH3hz7Kvc5oGstef1xXAcjWDJB9cBo9GdKmdYwhIi4BV4wcbd0qjNG3"
    },
    "name": "vars-r114"
  },
  "workload": {
    "kind": "database"
  }
}
