{
  "containerPort": 3000,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:86897f2c2f2572def4141f464cba647a5499a147299480833e6d27844580abd3",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/87"
  },
  "iris": {
    "deploymentId": 289,
    "serviceName": "test-project-main",
    "targetName": "aws"
  },
  "projectId": "58",
  "release": {
    "id": 135,
    "sourceSha": "8179e227990054268e960aa1ede42ef473b514bc"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "test-project-main-87.likelion.uk"
  },
  "service": {
    "exposeContainerPort": true
  }
}
