{
  "database": {
    "engine": "postgres",
    "image": "docker.io/library/postgres:16-alpine@sha256:721873c34ceb9f8d8fc265984940dc982404c105f19ad51be9fdc5970a6080ea",
    "port": 5432,
    "storage": "5Gi"
  },
  "iris": {
    "deploymentId": 218,
    "serviceName": "postgres",
    "targetName": "aws"
  },
  "projectId": "37",
  "release": {
    "id": 104
  },
  "replicas": 1,
  "variables": {
    "encryptedData": {
      "POSTGRES_DB": "AgCKOCYvAAN2tdyiT0Z5MGaCtYaZS104bw6Ev0+/EGI6Q5zxmCreDG8/NJw2AhPtz1JjHgL/loHAlf5BfE09XMXKIEUhD2/ORrev52t5KD+ZsFJ6WtMrK5cvSM/imYIYpQCEnfJdq1SeeJJjY44rc4o4OV5cmklZFcAgY4pwPdItrJJOkhvOKMTGJG+nGuuwHWM/rbuv1EJMbcxO/5Zve0eALycIwtLA972GVg524fsm1D8/Xg8ijFf0jm5bMzF6plBri4Ni3f8DEso7NQmJaY2Pc+bUOTLIMWYBRU/t0CwVpQDNCcTa+ZCK517A6fAiQVRzCopJTixOB1XKc8NN3IiSeshbvWAa/X02p4WdPXnXOTl+knFaDqDXcBOzqzr9lQ8wUWUqA0uOBoWIK8qhXP1npMHcBB+yTAAeBTik3ur53+n5HnAKMnrhPUfqefsF2WBjvpIXsZPbLuQMeGL8Yuh6asKHMqjP6gDQ30UDMeErRPqq7ljjc5nh9GGGGsVrlnA/Sg1wioz1FALuf0OyI0YkFeTPuB5xuqno1O0er+HLVIaHSzEORHaDT72331+hRTi3x77FCxdOBAJsc62OCMe9vL5srtKjsX2ClhAP4SkQmvIpE4owoYEyZzKEWZchjgqQP+Qx8oAoW8jFIFyiJHCfIYa6m+vofQyW6q+Em31GYYvxa5wxlql7mHhxMqL9xRoddVqS",
      "POSTGRES_PASSWORD": "AgA951XjujEEernJbVCz41qzS5UHOF1vAVc0D7X1un64q2r9SubhJ4CjzmggpH3F8O6GAWTiLAD2+IW2ZDlYuSr2nxbtkxSdzlEEbRUVi2Qw1/py+Mfuk1b+WlhBm6Q71trawe0DvOXlXqBZSxw0aBsL9u/I4oQoMVldNWvQKNQHVe4dG0Al1XkNQAB4iL4USy5HTKmUXOImjTraXLyllW//Ma2N8rAHAeOIauieK8pmZI23FGhV4XbiKM1/jV5G7bVNBq+Ox9ADW99E6Ka9epXMSzVXDN7VZW98K58R98l1g6IEjTR+3f1riLCDqHkKbfjuIXcuQenlp7+mexACZTf5aVvPRfx4J97xDOrPFvXdoFOL3Y8GmgqK1xNCHqcNjjAY5wcUes+jesehM3XCBkyR1N9+mH1HvK+u3IWqa58BopXYPBnPuH4kZ39iw4c3LugWhCAnqY1zRzVHlTtZIwj7itmERi8JJNaL6Cv0QDFkplJ+OFcwio2xOKnbAv3Ph6O59x+nVPx8UFdTTRLmIcyVNSlZMmMFBiCtYO79Hyg2Vnn96BpHySKyW1MpbGSmfmTl5f/5WE+Q/eZO1fuHWI92HlhfqvR1+My6Qdktve12BsRSabTTo52DQRdEUYgqcajzGdl3cfHtrwtZIRMTyFz1HNHr+MHAK2HxZhF+wMnBFJcSP9d/kcRn6+/NIwLdfnwkogvCMVYNCyRm10deL5Fc6UHKDGzyv1Wvr/OXTtW9Zg==",
      "POSTGRES_USER": "AgB4tlfeKK3dX0yxDU0aEEvatVgyVBbGc7pV7dQ5rE/uCvOJcd5yyG4hsPy1PyJzs2D6uw3KweZjAc4o7iSYQpUzQ4GpNBj6GkXuspfzSAMYXbPTnFjFyFzJexCctPKRIu9MpWdaxwgJTMnKsHEqZWNAZSiqxlH0jbxPqdmc/ceGF56cwnfpRFjcfCdWPVknqi//tyyRpEXcHT/gHT0PkeADHLxI3P070OjQ43NW9j0rl//C2WyJkLfRjlolg2Spnp4UNtY3ql8hSd/q7LfbSTmUXYu2PjDO/uDpBVn1LuyR65GeafnUD2eolBUFA91LaDwPemmotdP4ojsxEPgKjsLWgZGCrCRjxOqg71/Jp1/iUIal0AcLmNomFar/n7AzxGkYmiboGO4S3ISdAkJOeKJhXAGEmN15wFDcKaFrCuItudXPlMyMp/sBTrC3MF+rWE0qfXVPXy6L/crnoZr4RL9dML3tveRZeVKqAFOt9QYF5W87oMQCtZjZl97C5RsCa3hG96+6MqkjjxDI3oRA6zGcFrxB2o8e4y1IxsyQ0pTKDx3ZK2wcoBurdK7HMJGLI8U8HB7oqAmU9QkUodYjiT+h+mp2EQofYoLOp6JsFyuBkSwCB295w8MDNFTXJ3KW/IvAXo941bkLgjqHKH/bdoNwc5dUmUdfNYXwnm2DmDXa6qgxEPlCwXsXBwYFYp/TkGgK2kl4"
    },
    "name": "vars-r104"
  },
  "workload": {
    "kind": "database"
  }
}
