{
  "database": {
    "engine": "postgres",
    "image": "docker.io/library/postgres:16-alpine@sha256:721873c34ceb9f8d8fc265984940dc982404c105f19ad51be9fdc5970a6080ea",
    "port": 5432,
    "storage": "5Gi"
  },
  "iris": {
    "deploymentId": 221,
    "serviceName": "postgres",
    "targetName": "aws"
  },
  "projectId": "37",
  "release": {
    "id": 107
  },
  "replicas": 1,
  "variables": {
    "encryptedData": {
      "POSTGRES_DB": "AgA2AtQ4OqeH8GLLzC6fu7V3aPEd8h98GpfxAe5RWfMDVh4BSg2EzpI+7sfegth+ZNqXVKIDQLYQfhiULlsoMFnYCfGBinYHK2FnEu2Ppyf16x1ZFZ7X5XhHfHLQh+YU/Gm929ijv/5BgxtJtsyTjyA/lLdpeRsRrqT1Xb6Q8rz8SMHKJqBe2hz/pn13Sv8IeUGcqrAGiM/99vVLHSYcveBMFnRmsPotZ5t8a7cww1DCg+EoDJq8HNQioD2u5Qdls57OmsjkPwdoiJz9CDL5v8v+3R4ng6+TnmT55Z3/OT6GtC37UeDjgdcnxS4A77uOy5+X4w9m/ZZtnpPLdA+CQjJRqXyArDCKANhS7pyVg08iarD66+2r4l9BvUE2ZKFtHfl1GWe1eNgFjN0ZbzQ9NwRnXXsC1NVlTdR5zkn6sLy4isPx5e+wofNBRcjVAHQKo6T9v7gsE9y4evvFoXROKR9fXmxAJ9BzZGQkM3joZwUdI7MXv/QMDdmTcGAkexrwS7o/qXVVmvP2hLohwa6+S8dm6RZdzgaNnBZaHTVKXxyHcgJ7hnpYg3dHvCY47TP8FRz0wE7T0CnuKCndjnZz+5JS5v0HlncEHNvQ2DIAyeFE5OWC6cozBFSApb2ORyHzq0HWMjL/LoWp2h1nE3yy1mHblneSjtRsT1X580m7vaKNb7pZwDp1qv/vO34okZKTG8UDwKgs",
      "POSTGRES_PASSWORD": "AgC7PBFgOiIcCF3N811OOxePWo7ISK9dSbXVmEiBFRu8seQWP4kpj5TpVAZ3CTOrBeH1Fl5O5L+O292pdJEGOfqxRIC1hoEI6ndYQ26qPGvg+6aRW6BSPeYFU/cPWQvDwb1n9O8bb9jyr7mXuj//EHkD7Huy3zexwadttO6F3v4+CfpIdFPxPmkFuO0LQ0Dm7CmnINl1+zrw0vYBjcI9b6rYrstn8JByg2TtD3mviTpBe/chBYaOCdzo9v6ToB9L5Pf6ay2lIH9iQyHpxRBQqXK/NTFJRrZrqj07sQn6dZhRrNQNy3L6dHfMf8lQlR8GSUVQZCHh9yW4XdVVsH/XJNeUC/Tra0bDr5WNEz+tcw2kMI7/2BEek4f2P1Rxy8d8ywZZ3S7QopyfWnjrjPlHcfylRwoRD7MPGFJ7Z1OxT3KRxzPdsbXORlKlAg8pkkCDDumyKXdqLCW4hIZfhsXsc7vM1Z1x5Ao7ZXwoxeZMyawCEqUW1QfMYhKoQBC5UZllFpfr9HJ2bRI7eT4W2TkrLQhO2Z+tROmYaTe7jqqP2W+c1xVHGiKwboSVBSyzh/V7/mi5RoeGffnmmSgM0Ixs6miyiGFeFUEzAbY+kft9By9aOJL2j8Yu+vq/MJOfN+DmffvrqVKSGOm5zkaJI/tFRVsS13h3Nbs0brcLshUti2cWJv1lwwyDuqDNv17qSmyf1cSumIarlKY786sf9ez4zNJD0i6UtVSF878RSVz2lDC0ZA==",
      "POSTGRES_USER": "AgA5RIkAoe0tNQCnafytgUXadWYhC1B2JsDJtMW1HUG5scPyeopU9v/veO8ox6wZ+OT8GiDbR/UKbYjOmqg8N/z0T+uJaXD1oB2aIUiWhp3TVarXv0EymWTYnMUQCeT+m20ZdIjwREpfCpoTK0LcKtu4DZYx52FIOR66A/mNXHxSxphOdthDPwSPUpYqHRod31WUaeLt5C11N6bzRQaMV4X7XVIiDt5UGE1QVaqPD5mGBJmTrCBSoAqhnUoZ7y+CqRKJLedgWe/kpaQvhhBvEAB8XYbpaUo/AP5wALbrPdBvk0iFcSZ8k1WvOP/arUyobg7twmTdHnpUZxyEzn6Zf5ZZuuMhXzBymA9FrVjCzRx+TjOVfkvZ+gflqcDIpgPA1bMaQBxqKbLiZjnza7R68FvmWFJCHalW/CmF4AKlG25buoC8tv/v3rl88FzzN0E8aDAqElN1e/e6hKL+Sgx4nzQPz7QvaRezQ5nRI2jlXlfqdbzcV+iUSW37OUvEfn5q6/nVkIEbe33TpLA2Fis6QsX3RuKciL/zuXirVfYnJdNi/hJKIHkaXBwE2RqHweZPplyafY4e4+JLCYT0E8T3FAPAG10S8smFSIyTT+46z+0X2e6Tz2F+o23BSZUp08HUAM2iBi+JQ62tsRrsD/6eyjB6SEbVzCXeF+g9kAtrr+3FDhECve0y1KtRcI6lPo5jr24lB9gf"
    },
    "name": "vars-r107"
  },
  "workload": {
    "kind": "database"
  }
}
