{
  "containerPort": 8080,
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:052fafe9c2a02ace9e206d4ecc515d66604bd78bd3746ac4f71d37368d716918",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/23"
  },
  "iris": {
    "deploymentId": 48,
    "serviceName": "temp-log",
    "targetName": "aws"
  },
  "release": {
    "id": 36,
    "sourceSha": "54fa8072d9fbf817e3352f8eeee2344f37c8a813"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "temp-log-23.likelion.uk"
  }
}
