{
  "containerPort": 8080,
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:9e37db2bb1325cc517d20320404b7c84fb677d22bb62d9fbd20036b12b4028b6",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/7"
  },
  "iris": {
    "deploymentId": 16,
    "serviceName": "remove-e2e",
    "targetName": "aws"
  },
  "release": {
    "id": 16,
    "sourceSha": "446917d6b46febbe2b4f7927166a0cc501de667e"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "remove-e2e-7.likelion.uk"
  }
}
