{
  "containerPort": 4000,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "hostAliases": [
    {
      "name": "mongo",
      "target": "app.svc-46.svc.cluster.local"
    }
  ],
  "image": {
    "digest": "sha256:02a8a52c939a1fa536e4548814c6d19396306e43dc2348a717782b67fc17aaa8",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/47"
  },
  "iris": {
    "deploymentId": 151,
    "serviceName": "app",
    "targetName": "aws"
  },
  "projectId": "20",
  "release": {
    "id": 83,
    "sourceSha": "03c736bab48fa2f9e24ed7950f0e27c11138e877"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "app-47.likelion.uk"
  },
  "service": {
    "exposeContainerPort": true
  },
  "variables": {
    "encryptedData": {
      "MONGO_APP_PASSWORD": "AgBXAxmUeX3T0wk1EBfmu0V5ipcrulGRNTzAwjkIrtfv1UxUx5dkqp8i8+WQAZlb7mShx8xzmCJ7Ge1ABjlDSgt7ua9YzVjAXGIfF4Szjlj/UurUjDNhfcf+qzjiEYyFDW5ry71uDjiUuyY0ONf+IV4tfScUlKLjc7HAbuA0wjkz8yh+XN3zttzNUJK2WeGmthPBHizmFDl4UNSvi3K5MeQYoBdjitMB7LgUoW6zJpiCKy+nW9Lj1+bOfr6/q5T9xhZsNEy/d4a9oOOmTxFvElkSpdnywO4rrXoI5YY5BLXNENqS6mgc0zp/tg+KxH9fsxYksxdKHKbjOcDD80WcnJMybSv3GWxO2yxFAh6pOm1+StMGpp0wBHtr2F/x3a2PbTdC2GFwJuJOtPXCSzY9oZkeB7rMpc+F7OZalbL0ggqT8hvvteZjE/5YQP6tog33Dy3bxNQgovZkE6T00OxcKIAnoiCMYMDJId96pxJLZsDBC2FkFUMhWku1uzzbg/xsMa7wFS7IoiImeXq9DEcY6MvW0aBLHUOvIYfzevALM1hYVx+nbpP/2bFLeODweW/7w4RiUxQ8+q6PycQpi4LWh/MrqwggQVWPPV2a246pwkIC526IbthLXrJSwbpw0etQoa1t8Gfq/iAnUAL1D9CfHctZJSA/FhAqaDNWZnJJilTUZnvZuyLe8gUWZqQdGkK0kELGzGQPAPQYe0ygcEZK0vP5hlbxroLtAqBI2KZ/Umb9QJYrBA8xwgdaBpWJ",
      "MONGO_URI": "AgBseelspQQQ5wrdU6UCWx5yC3sFgRGueSBJJu/3YCH15RuQVHfdLApYnA4d8gQ/PcWwhuAbRQZscbYGPog9kNKcnhivyPTekr+yn2B61Cc4JRThZeHM+hAodQIrYN4oFZfatf2qyeE5s/654Bd6ExwWQoLjFuB6LPnOsIGP56yuzAIWhP/LsuYPNO2UHVmiMwDc5z0KmPMdAWaAiI+lsuhJhLPDBAfYzBIxW7HlQdTfL2Ripvb+CckWgm5eLz1yyFCdDWweR+3W10bScmbqV8Lwb6LVLPrEyMZjehcXTNxKt9KLufqdIvllbb5m7v2rgbvl6MPJ7rm70FpMLieFUwXxquis0O7oO3QHbMz8mac+gEyT6tgyS7IxkKVnK1kecnzqq5Eb7N6u9jNcpmW5AkWEdd2RXZlvWY/0WYUuTgtLvDq727i4qpVuAZAFqR3CQfh0YuCajoKUD4EFknGZ09pa5ADHw4QrMEOFdSl4HHkZ1jdQLfC3ilrUBw0NBrXOFoJNG9wDYJkxBzd73kTQ4vfckJ/Fj0fp+q3hjq+Zq2Hbh+IirrE/6sKg974Fa5mlK6CrncH0WXZnL+6m7EcE3oHghZp14IM9GF4QZt9Ska0PQFY0lkqvgrW7/QNa2qqB9irlFOWtqZ73wCe4dFbVOjNzff1tMfhjALF1itd/AZaFfZbZF//l4VNfdF3gL6am1vcvsYDrYAhMhEa8RK6g6PwWVDPJCPgFMAkwF8S979vJLB30tmB3m/VRZ58rJGVmF99+YuEsPCsB4vGQ721dz8/U0v4LIt3/+A6uTml6O+cU5rbiti+xAn/AEWwHx4bbFt9Ddve7AvzDXzLT6siuWKkT582cyYMzObj38TE=",
      "SESSION_SECRET": "AgC1+JiRgFHYolGvha8jVv2t9llcw66L9kCiEit7kZyQ1GKQ6HFbrF6MBBcYAhIhCjhtUudlIxVjqoh63i9cDeel/kkUsRk3tTECsFfelnbW9rihYkhjJfT2AAiHprAM5Axthx4ZwzaN5/FOgtfqxkje0sfnpUIp4VLvp4LvdepMzWYWWh3iG6PCfj3KFBFrQUME98QQd5hgPi+ZLWQLf3dt/j7svSN3Mi4Ve/zBJipSTE9LKrOtBc4uAoYyNUocndGGPeRYcSQau02Tr1rBI5bB/SBlJBmGIbDz4gAGZoJwiA2Fy4NtyjE+a0P7fMmpcmP2wJ8kHfZjeEfZMSMeoGzFyLJFj4zwR3J/8QRHfrDpqGrXSIpm1sGXk+tSxHOIsGcdqlrhMYp9bQSXzm5jJXSilcz6dupXHx90ybnKSYjNJj8MP+nWsdly5cuCbcCaiUl62f4iSQU+JpzZ8m0eCFRUhVCGRG9NWT1rS2aIFGSkUm/9qd85liSllM5wg1orkzgLT8nvC+/Adj3FK6zqXZb9OTtku1DES6rkuKPTiGKse+XOVkhpeqkaq7um/i/x7lTobi5re/DkCiCipVd01Rdu4o69q45Ety4WohtuKRdqkEXtxX6s8D5wd0esIP61qjBJgF8RAh5fi2l80f7yxLn3xo3LoD+I6yf/Zarmm/DSWQbYpXQqF+PMAqOtaHe858mhqoFs2vkPkBZO1lWJofajJfYTqCxMHIVUu4pT9t6/CleFjlulvgrEgedq+HlNFxbN+5f9E2QlqdsLR8KWf8X8/MTtp078eaJ/LNg/mE7OtLFR5wH0AahhdBDBucwksEU="
    },
    "name": "vars-r83"
  }
}
