{
  "containerPort": 4000,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "hostAliases": [
    {
      "name": "mongo",
      "target": "app.svc-46.svc.cluster.local"
    }
  ],
  "image": {
    "digest": "sha256:338b9e54943dccfc8268613fac1253bfeccc984eac290225c6e15beb568694a7",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/47"
  },
  "iris": {
    "deploymentId": 142,
    "serviceName": "app",
    "targetName": "aws"
  },
  "projectId": "20",
  "release": {
    "id": 75,
    "sourceSha": "54fa8072d9fbf817e3352f8eeee2344f37c8a813"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "app-47.likelion.uk"
  },
  "service": {
    "exposeContainerPort": true
  },
  "variables": {
    "encryptedData": {
      "MONGO_APP_PASSWORD": "AgC0l5kjoHrToqT80J+jmMxthSDAq4sCvUnPicIuf0U8quZc5ZOU1GGStHGu0LHDF97ynhlVH2XKZ/CZ4YMxsBFUwHU40eTs6KwkGRtbiN2gmwZh4cCm982R0mk/tYTifeMx1bfrG0MnIrhYlBy8XB3bpKWrxnoGJmccpMUm2dhdiCaPyDy7KJGbl09nHs6mu9u1znk5Lh9cbQwqP7hBAbMn+SAWoerJ3w8gN8LCKMt7Ll89aav3HO1hnjjB9kwZo/RGxvfT9wpphnH4TfM0EIRttP/e1ofvOYUyG5HCMCtEA7u+tP3K+/GlDIlO45Zv7+WbqeLhaqGbEuW0/ciB7eSlyetWNQZ13dEVzyAZ+TQKRzMMQseLKyh1vtixOdkaCJdn9KqYPGDT7EdCXz/eqC2ZHcKuE/E0Vh2+Wp/cq6RL1D1iRm+gzp5Mb3pZD82NilGMMtWEyZNnNGBN3BOycWBh8S9EPHhYgJZ8h1BKLXXFmwx57NcrJpP2SEceeXLGFwYiebInycidRGDhYyGNV/m08/GQqpAk02KOKZ5eJmS+8HGfffR9ui4a0olSDsaKKhyn40XYzGP2IITMYB56uj8MXt6VEhPMWeUsxIZ+/rP6aMw7uSQ9KaKm3GRcACVItdeAl6QGqML1t7LJDdCKV3x9+qI/VWXsnvX7uAifSnNCo+1Mzz/OPM/19ZpnRY/NPyE6IJ6W2P+Qu0HgT/0XZ6RK7METQDN8KEqtMv1rRfHlugKLs20r7sZlzUzR",
      "MONGO_URI": "AgC4XTzw/y/DJipXwiS36SkrKBFP9YUGJ9Vfje/Wq0z+UwYqklMfKOOgGAc8bxK/bP3xSVeNeaBiD/2VC9KrFK+cPXhDh4KXlDhJbcA0cdvsn7TTucXXcb/fksgpHWXojvBJwi7WE2QeT7wztwd/RjK+moYZDRu6Kwb2JwzmTd424gnZ2CClIrGjwzsKdimYQ92cUW5TL/IJRrjcRxRLLH+vBUSUbRKMi9tWHnrskSyFMpleAHZcEvRASZI66VivucAjmgNLNz7bCZNw4julPyxYLQxd0FcYsNazLzLf6bo0yBWmtNI07PTwoZ4atwLQiUspQiGiBW0C0yGvX/cn1fPUBpr5hZpKohF/qW6wgDPUD4Obn7SW3ABbtW3ROPsLjBUvT/H5TRUfjYqKt9BviqiLEQHR3MuFLACBXA/BivDoMCPIQh6duLK54mem1MIcHUXP7vzLifH1r7DgFhWgUUMSlo/TO+pe14rbA7eWc08baHKKTEG4E+fP7XGJvitFBV+NKasZWvE6d1mKV/U4xGr6/2IAbQKWTQXlieyyeZYz7yAGj6R5IKxy+WfXFr1u03vUYFWNvfsxyQZF9oOGmcKBye1moISnVdWs/BvTx8JpQxS74AATQltM5c0kyFrnF4ivmiZkUspKktCX1344jY4JvH/gvJVByHoN8j0rrw4gtKUUdQxWXDxztytfc5pLkcqQcUwHPTGGMj5kxJjLluGW4RUYlpur07EgQoXoWQ6GsaMxvOucC00LXU/3OR0gcjz15bc8jpatXRD5pQ671DxuhAsDoNH4z6AxfkzjQdVn8+uSvxLmoKVUBX1y7Py0nHSWut+Tn+3QlMki92aMJT/WDLos70kcyFHifJ0=",
      "SESSION_SECRET": "AgApLvA7JCaLYJXoQ9MEjzIA+gueDjKfe/CxQmWHqQJgJzJTQLtuoZSKvWSL59Lg6Y8M5KnzbT//+FJzi8z0hOxzv1G/2/Rj7eC/wxMf1if+xbvip867w2qO0gzWfI9W+OXHtLMycN+NRkqDvWq8urN/jMDID/n5n1h06leoE4UdbStela8t87tLRnNKeAniV6GKHXrX3ig5+fy5/IN46JDwWOT8+5meIsm5xxSqf9YtJfQ74qDID5gA6bZlQB3RsRxmiqA97L3uusSH40tspv2NGMVUDyI5Uu1s2Xqv7DqK/ZQslQZopt2sPVzOEb5h/KwWpG+z98DC1CW4vX1iCjWj3gfUVMikvg9L0wshsVVKTOOobLn3btCx5SJCkjYNgxLjeHG5HuRoEki12G2CnaohzfmJhQdXE7ljDSyPbVPiKtKSQlhe7PvpeUwddYFxNMp5VrQxTSrGpK066Mv3aU/4Xx0HKYNIWWurwEF1DQl1wFwKomJjU+DjclMM/DsTdlygr/aGzKuJGKmRFXKgZ280sydM6vk9+Dyfa0C5Xuq8Td/QcwSH+WU3vbCtW/xpH7fe6/O3z7/BBe7BWrphbVWLXB5/vTzTfPFGeS50jR++TOCILSMyjyx59EsUt0vreep/Fzew/rd7XBDmHsyoMhK8uN4fIgOnuJTTVcc3kYlJ8XcjHJCcBonMSTxEfKvTYCMFKcMqXSCwiWisT9VVjZf6VdUVfS1KQD8Jg+5KHANwZwA95bgfK2ELCuKLyFF/5HlxEUzqa2tUQEioqz2sTCHDL53o0gmSP5VYAGmn1pxokfxpQ+6KZx01DtPxBp0y00I="
    },
    "name": "vars-r75"
  }
}
