{
  "containerPort": 4000,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "hostAliases": [
    {
      "name": "mongo",
      "target": "app.svc-46.svc.cluster.local"
    }
  ],
  "image": {
    "digest": "sha256:941e00733cd4e8c70883429de989df0cbb14fe587324d97965ac94dbe3c2757a",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/47"
  },
  "iris": {
    "deploymentId": 176,
    "serviceName": "app",
    "targetName": "aws"
  },
  "projectId": "20",
  "release": {
    "id": 92,
    "sourceSha": "42568f377943e77ee01fdda30ed833d96f9defe9"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "app-47.likelion.uk"
  },
  "service": {
    "exposeContainerPort": true
  },
  "variables": {
    "encryptedData": {
      "MONGO_APP_PASSWORD": "AgAMfdveayrfhxSbjmNb2PgT4jfOVuu2NFm4pI5qXwHphGj7olwhiGsKpMWxrvhjZ8aJCz1XqoSPtDZBZirOUtnmygv+DMgGiEy4eunCtTy+2QWMr8Y/XIxvG6xR3tPItn5CVe3eGu8NR7QKNmcbkoNuSBLU/IQRvUp3K6X2rxNd+fops1Il0vsjPo77VaHKDGWhaHJoklNlin+kuSl8gYTnSIZbsVwzriczplKMsmDrj8Gdc0pvzKAZbg75a8d8BpxqO4lD4FSjXVyH3gW4xSn18SmtuDgfI0VDJx03qtyg1bPnpCWHQMtbcMOgNmHLBGAxQ5Xa6VdwfSW+jrvUXaYnJhCmeOCFd0XLa1jyEswYF4OMxzXNDieVThgSzVqaYkwJ4n8qLYsn5I34Cni+IdTM3wYMj3ZzB617lBPD0lRw7lIQ+sX45ExtDxNQaG+pg2QvGKAo4hYOepPoL0ioQISNHJrNmKWjpeKAoc41vnrr81VogVK7yMLQm1Y5t6gKNWhf1hc1ei3NRWRpk6JpD95PL+tR3IAwifIJE1bEbrvfeQ2bHjG7ZILo4ICofel6KTLjtYAhwn8sLBkrzvEY2XrROA074M1s+t+0Ea5rVoo7OcjxxrcsiL4J1QYVjZoyrjWIIZRRsGncUSQ5+4TEFDngKMBYyHd0nuIJsh3/mIxNLeZUW84gp/RmzGMGmHHx7ulJiIUTVYqEKsGqfP5oiZaJ6ufUGiMKhJ4BDNUSvU6BbJpiq/GFl8KgGUiQ",
      "MONGO_URI": "AgCuMI7c2hgDk08lNzp/pQFRMjKlHacv0NjT4RzFRiCDReLXnyslY6esOQIzJImRz/TT7OkK1ov2UuFXUGJVUYAZ2snmXrUqckBcd++serOhLt5leNpCgR6j25zPfNngS1ab3zivY89mLbNbxfdsKIk3eOD0kdJ2AWbyz0yBIAYKI+5ZVa/Ih8D88hzkd87/PDaj88GQX/SLqWltuwVtDJZrZ2FmwbVn9Bc/QZzF2GHE7TMfwxtCJ5aWuknQVSuQ0DmHcIKLMkXiu8glL5I7fK9PzhhKT6yvOm4qJHG00auYvbm4UsrdguMRtV+Wcef4BDE7p8lBiZ6UOiRUHVFtYClnGRmuQqTvjXqXzeZGgTaGojYveNndRJphHqIv5MphtiRzcJauZsM6OimZukCFr4U2mrL42joTpV+odFUjeepdkou4/vpxJOkDwTXE7k5PYPeHiaYlCYjYM/ONBJm/84/7UMw0zCpm6fGrjwSPV+9tyvRaRGDNq/6xzMH/GIOrJlDJISQF34TyuqxGTGSfJ+laP1LGXnooGEAum9UhLc2fGBeFjJtx4iHX4F8wtuS1Byiv5zAuptX5qI+Sinl3dggAiVivKEkdtsBbpBuvXI8DjJoC1NfaEUqr8KBDAEudODnPa9sJl8zZ/Ymop3iZo8AhSP0V/+4AsPwWyCjUn32UpDciWg3KmTmlnAzcMKqK2xFiHXtL3zJRaTpXsTtVus+rF+LrUURSySZffO5IcoD0d9/UugGWPKdOELJe83Vfk4kn2G+ZQazOkHB1d15jZrq3VpzNq0CxaQwOHgw0250MITkjbVauP34c04CcKZYU6OeVpJgjB6Dq2fBSfn5vE4YAGU9DJBOgCXNTuiw=",
      "SESSION_SECRET": "AgBakfACLvNO98+opzxaggpvCgJ4LNhZiZFaBnNKBUjqRCc+g1bGBVKmyfNKx40d5ye3grNnl2bxXGXiM4FXORuJL7FGb8Nx8AHxmngYN7HmKcQLXigeUPhyBSRD+aApT6ypURL9kfLsqjoEs7E3jb8U5NGD/VhJgXgknM85FnDeNvSvOIe+xeBbCOvvCyT2XfKi84gCiz5TQ3omzzjaetC/u3zRl60GfIB3dJgBOEa/pXIglb0FA4wLk0kS+RFQFyTWvgdSjaRjy98iWWDcuyzjIFWieUAvCtC+k0EgZ60ffCb4GMkXPSNb8qRDi5TLAfgcRAfvM6mjYOIwPcCeIfY4S3Y8PjZc9ORyVoW500MHauhr4oKMfevGJh8L+N5NSPCUqv61XYN5X8G0pKOWuW9ukMoUw98OhznyBkMPLfgXAVOf3xoG9ZRoU8Joe7+e6gAHwOraGtT+sooRVXp/8s4qGnvFvzP4MmeidYQz8tmedl8mwXyC7/uWRGK7/RthHpfdzf0lB5T8nRXzXxGnCcHf2S6JF4F06tpcmavJ1/wrxHIIs2dz+zPal7IGyfuUUZUtid04XVnr0IkzQtH9gmR4yEtVAWvMWDYUGWgUri5EXF8WWnbzdraOYVfLgGjTSnmnbM8ByEbCYbUBhSOiMYTX6Xe9Dlzb55YsNGZ0x9pakWmU4gOopVfGx7La0hmQYEucw6Z87c1m9uvQX3KRteDyJJ5PfAKyudDU3EbGMJUg1sRSi0T9vLV5ivI0rpfNXHomSnTa7rAaixdCTMntN3xC7T/rDzUKAciw1h+Dd5QShWcL9L1PjBZSq5LyWI0C50c="
    },
    "name": "vars-r92"
  }
}
