{
  "containerPort": 8080,
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:5cda7628c524b50be32f67602980059a1ebea81911ea28eb83da1ca0eba1fc2b",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/22"
  },
  "iris": {
    "deploymentId": 44,
    "serviceName": "test-project",
    "targetName": "aws"
  },
  "release": {
    "id": 32,
    "sourceSha": "7f061109e2d2b010c38c2c7e2f016df4842bf0d8"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "test-project-22.likelion.uk"
  }
}
