{
  "containerPort": 8080,
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:df7d739f215ce7af77c0055501799591daa9fc711cf033ce5273cdec33867d5f",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/4"
  },
  "release": {
    "id": 8,
    "sourceSha": "ffdf5a8e0086d1b6f1180d8d62d560d6489aa237"
  },
  "route": {
    "host": "resume-4.likelion.uk"
  }
}
