{
  "containerPort": 4000,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "hostAliases": [
    {
      "name": "mongo",
      "target": "app.svc-44.svc.cluster.local"
    }
  ],
  "image": {
    "digest": "sha256:3892c723474163a7aa568b392eed97ea4824dc1178da1aaa02e029911244f135",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/45"
  },
  "iris": {
    "deploymentId": 175,
    "serviceName": "app",
    "targetName": "aws"
  },
  "projectId": "19",
  "release": {
    "id": 91,
    "sourceSha": "42568f377943e77ee01fdda30ed833d96f9defe9"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "app-45.likelion.uk"
  },
  "service": {
    "exposeContainerPort": true
  },
  "variables": {
    "encryptedData": {
      "MONGO_APP_PASSWORD": "AgAu98uXmWCGnu7McqM3MhZY/A0qnywU9sjg83wBZxXqtGNvFOsekB0423QZQsqV7h3PCV+j4dh/vuO7fcm0v+Ram+qnRM+yMm5d4OsE8ApBjUk6+SsL6tPBtioEiA+vHhSmTS/tfHlc/qmBesf16SAexKAC+MWhd+0V9TBQDnt8IVOjrclwK/cuDwy/zkQ7XqTvicbUuAKyxkq/qNeq5lZIiqysXbSRQasrVg9AL75S4k74Ud5z2SFgz5XGUXQLeWYrrUzOtc3LaEIX3kUyETETPgxojZp3uJ5QB4Douq4oRiaiNHm15A1bIQVURPvoqPJFRffJ9HAmsOFodS40K45MrPxibd6YiPdBbUkjp0EWe4+s9AhkR8bjWe7H/e+hxCd0ONQeKmyhBIBxMurRlKbSMW9zkmjypfuHu4oy5U1FZcrmgY5wJtbLn9NFKdVmRxGJbciioZaaxszo186XhDDugGALPHljP0Q88TSUB0TFk1jQbP7G4BJci68uAhFzeZzXdRpZOfDyTxoWuN/OfjYzlQVciys+KLZ9uNrPHpmIoE9Ggk+tk8LXrzbaokHeF56zfP761ygXlxn1X+LdElC8j0gNU6qTZF+qe19h05M50Wy/qbp4TvZmyXBHlvurRbEg/6MUMBqY/q+ilPCZD7i/jajmAYxrPRehqNrbn42NEM7K9hIhhRfIWFtykuwZy4yS5T6aAI5NbB9FquNMMjtRU7bhhC+Q5ghua5qA6HL7wC1C74WQhoEmAuF2",
      "MONGO_URI": "AgC+59ybSsMR9ywo1ItbHNdsJfLfPvyk6Jnwt3/KwCuIG4OZcs4GSJTW9XtCdlBfwcDqDzrJiabX2QQnlBlDOiPMyExG38CCy/ZovcIKISfYc5P5jRddEIqa9Z6tPhSp7aVwRrMG1IgcLw34/aCU8vOpGtXrOzSSmtlyzY3VXwcnL4nrZQMrupxpn7ruK4PbLhD02BzQJwmpCrXbaQFAfhvOAEm6n6AMET4ohBSKTGkJRDcewa3kjGFgk3ECDpsb24KxW37Gf9+fgDCHQScNAuJn8hcQ15gJBIcOulxTGDY0unL7UH2JBZ5ZrEBo347tXgtGz/Y33nNIxRa3BYjBF4vMDAdvq9MsjRjzfWZfpFkPFkQzT1lVLhbba8xUlF1jpT2mUXR1VLYaxav5myCtGQyJx9tjW3ywqz7c0xdp0Yg9f49ZqdZDwyJ2nFSZQzxFmD0Apz/djIYo3p3/tfniclUDdnFq3Wo5IgyI8q4zl1NEa3i4Ou+IxkctHvqDrG/wAb438xAihLjxUfHlqzkV6YNB/mKHvxx3aVpw3lWxZOfanRkUdQ7rWORhRMNB6npwemlySjBborNU1ZTbm1optIxO16D6LvAFhrg9F7x6TNmU8vctcnxtMgpHta6bgNr7ZcvCG+NlNt8dwWiNU+Vzz8BzQ8TYC0cUsZrflX3X9nbSqnXsYdEu3dBUCPNGXP9xbpE/k09WDVdX/SoEpJddh0k9gkAaovPkys8S0Vn91dkStEv/7YELB4HyV/y5mFm7m+zJKZUxWFkkIKezH+NgnIkciETF3rLA6NmmQbAP2PSXdAQScAFviqwOsNim374WlaYqlZbWFZPLMkHeMdbjtSr6LmTJv9UJ3GeeFsM=",
      "SESSION_SECRET": "AgCdt7bbaP9Xfue0m59m3+eUqgdSXxlz3o+IcxbA718f53yl3CWBhrFj6rm6uQxtNhhd0qMkGYXTQgpH2pa0LsZ+qavb3hvHyuv5tQQT3bnL/fV1lhOeqcBE7L1LkhF03fNf/TegairPeyWA6LZohhQjG5Cmups1H/AtokzZXqjeV6GffKAI3isBrwf5T/z/geTEm4MCtyAar+2wiAfs75w4gfBHmlNZWpt74iYLKDk39cc05G6+6AoQmbmVaWKf/powsUMOKyILowiha4H26eBa0MBnq3PQCpxE6cTtGREzXx++zZSGVJ75KIQFPAoQ1CVv8UMRIJ2BHHYc6DhAyfNSQsRiZrBafKy97s9skKf3vMvyg6UjPWdYUnXxrQriObvRwMIqqlfIZnAGj6ZbjI+QkpXjnPeUovBi/qS4QEsITp5cbbNkLI9WDGFGrZLar2GqUDG+7p7Z1jEe03gWyU1R18LIDHqQw2Ryz2cLczfLCvFB1oMoq5UQ2aYFflHLRLCDMHtpf0T+Accws3Bs+GnliZe7NZIhxlhRf7g4IG1a1gNZrbY6wkHXk7UfIXqmLT+ekdOafyu02b+7A/hWeBIZMzqqczV75fWYgg23A9S2VV0Cjw2ndOmvWWAtRjLT4/cloAUxjs9kBWARPRootnXU9dxKdlKUgR3jZ7bwO4iHADbqg+ymUcsEDCKxmcxMg4zht18vaXq/DsRfXDTO6HunRiV22kvtLV9Wp8mM2VIB2jn1zRqSXFktg2kQSZyLwCclpcUAi51ICXn0nVUbTS7rpVmqFgWcA+c18dsCVl1x8bO5LhxWNg/1StDT4p8AlRyhloE="
    },
    "name": "vars-r91"
  }
}
