{
  "containerPort": 4000,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "hostAliases": [
    {
      "name": "mongo",
      "target": "app.svc-44.svc.cluster.local"
    }
  ],
  "image": {
    "digest": "sha256:ed8faf21d396a5028f372aa9343ecf46106a7f53670f1097781c8f025f54a4a1",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/45"
  },
  "iris": {
    "deploymentId": 150,
    "serviceName": "app",
    "targetName": "aws"
  },
  "projectId": "19",
  "release": {
    "id": 82,
    "sourceSha": "03c736bab48fa2f9e24ed7950f0e27c11138e877"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "app-45.likelion.uk"
  },
  "service": {
    "exposeContainerPort": true
  },
  "variables": {
    "encryptedData": {
      "MONGO_APP_PASSWORD": "AgBM4S9lmyP6bfm+eWZ9iAm2qU4GZnbzmaTzBfewbAMRWgur+yP8EaZEZKDyrkzneG2UyTGBoI5fpy+3p71gYAVlpg+x/bQqRC83ASblCj2Ga6W5Y2vdBKaQc0fkJstwmCpoLcuesLFx2JGFPNtp8HJkyZ+QiuQ3XXfbCjBNwlgnkqOL/7UblIBHrIrktkJiuhhfMOIeGCpKUw531csky6TL3uSbwwhR/jsjbsa+ozwDrbCOUOtXP1adv8UZ/igxgWCixCPn6a9zfkrcS9NFI5c0f8/emlqVl5bGacDls6l9JSid3FB/S/znyzF4BWyBEnozF5PMrD1kERLhz52CeYLfYGAt4fCkVBc14woF1EqkyiWcmjx+JXrHFegDihlSGdQmP3Q9pRY2s3F/mq9bsiO2gYqyP4noxUZ90AXZ62LNYvU0TRgEJU023xfRSggrKm2tEwjamsw7LmKyo/hj/isUrYpYUyhQPnigHMFRFuw0hrbLerRpbMf6eZlQMRCqppLT6X7XckdHpfU7PiO30o3Wle2S8g5+3hUI/uB1rBEXnJ3D+GkKNXq9ntiIQh7bmXIHyZh/CZNLAN11emSORekR85pSfatwQueUDv8trBHfdUeRWNmCDfVIR/uFQcwC2/dud1CnyBHG8NJV6S97Kj3PW/nYQoRZYgfF4yk+7eptdiO3vVCjA33M3SIqdqbna0zg6jkPXwupWUHcvuCkuxCt5DXg9oEdFDel7hDYKtchbJW29OSX8shTxuFa",
      "MONGO_URI": "AgByp/Uq8ZoaH9treaq34rB0dWRbtrWclBGsOlxwTgCVsfHI/mePB00a4rRBt5cQaHWYR+hGYfDfDoUP6CZrCss+LRa28dDuj/U0lFtGnELb8IgZrAys7CRbOJVv+RrL7Cs30PkGBluGLQi0xvmTIkqq9KS2yt8lBumO0uVBm9uTjnvT7E+ClMTzD3VU0IG3WYXkbRmSlFdgbADBIxQtzvCRrOH7jSRAKkHYQOBbUNLsJ6iWPxj9WQ4BoT1U2cpelz0V4JUIXk1D4jiW1iaRwJtEQJQ0lLHJ1pCMvdJMrQMJl1uYs2aJLVkHvFJejCE8nsqY7Zu5e59dpGLyMKrCLK/9kp1rmJu8/g0jvWuIQpDQXcc2Cilgaak5UmbhIicj+DN5VWk/UxlmveK6VmVMaXAHpJPijoPnDTwc2Y9NtPoLta8qYJMwhN9QOf4D3PYPRW+QgWQHfIpA4neJRDUO/YSYm/+xMzn+fWkzjOSkBZcRtCZ1kNYWckqc3/xR2oGQRSWGCgct2VmH5DeXq3RI05FwlByOfUjpToWhgkozdtIBDEVyZDHYRQ6WdneQK01uP6Xg4DBjU07jBuwkDvkK23oOwhNs2uOjMZRrQ9acTzGP5qFiPK14vlaZlRoui6geWfp/ZgXnA44VspTShm0DbrS7ZM/GBmIVs09aPwrXjvtxzRXrNNXKh9bnNbMfpOaBmW44c69zKDMhel1wvJo+dq7W/wntiG1kwy4OvLnLeMmc8YrKmuMQcASuBubjMnCaMb3fEbH8kbCWToo+Ilmyj4OaZ20Ka/Ic6yx9L8uLIfkSrPfsiXKB5CkS9iltGeLiJtooqZ+cr0/AQASO6MNwla3bzB7ub7l1gXbXMto=",
      "SESSION_SECRET": "AgAp8bkl5lk8yoxsGkIV7CW5CYVJPMLQCOxmbIi2PX5zUjmkaFGoqrI1As2E6mGZT2BTWHg3TkAx4tzQsgQl1lKP/M0SKNKBWEUy0VD9yrqJmzNrTJDowj52FcduLdZ9WzqTIEifAM/c4rHxv6JA31LtxPe7VnjbHxt4hWhReBzf2O6zVYARWV6zGtZFzOJqJazEoWYEtOYfPVsBdKKh3xJGHzETxoN6l6tv1CT1ollBwKPzUCAdhG2pd2xY7MCs4vI4x0MEUG+tTZekd09KEoPwv84LIXQcNY58HDnTdS9IsKEZ64B0QyAGHVwxQwB17is93VXTNYXLxUD/KUm1k+5lb7a6lNNUDKcd3WYQdQrutOgjyKgG1Dq52Le6VjkmVU3oJlh+mBnN5m+J2k0FQvnLzIYyhhP0vmE74+TxgRj7PZ4L94qfhdmUXObzyBhNBRAtqGeeEo+D/w/o9c2dsNhqEHgco/E8cRwiopPUOOoptkCK8zo6FmyQjZT1kcVipNR9x/ZyoBAkbzfQm0711qKnyALztgJ+1gIkn8GxRLueb+SnOfawxnO2A0PzaleANsXPfVYQKr+xeVNaSUwus8ol5oQZGuP5coq6XEIkK9zGQ+D1OPrH/LWWhjdmk7fTj7imv6KRvpWL6FskqFe0REydLAF4lOsA6aMBFf1NUPkJwFipyiqbct9TSiTBXeqXNdEnA30L4H5h2qhlUYI34SxbjB7b7vC3f97fmMJ/yfIseBHDzjHFyaT7FIhes8KOSQ4ejBnPC9YF0jX1nkYr9m0G0UFea606+2c+Ph/ZZd3hrvzS0w5BfR34lkyUnhvZ0Kd+qTo="
    },
    "name": "vars-r82"
  }
}
