{
  "containerPort": 8080,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:f2e3eae058c67fea54501af464d50e48e743f35f16b18059be1539718e41a72b",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/54"
  },
  "iris": {
    "deploymentId": 169,
    "serviceName": "temp-log-client",
    "targetName": "aws"
  },
  "projectId": "29",
  "release": {
    "id": 86,
    "sourceSha": "35dfaeb2d2177e8412d1985e6a22dc772631d1f5"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "temp-log-client-54.likelion.uk"
  },
  "service": {
    "exposeContainerPort": true
  }
}
