{
  "containerPort": 8080,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:359ed94bfbcddbbe55b89a81c99c4ed67f0dee60b03f425dcf4201a870eade2b",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/75"
  },
  "iris": {
    "deploymentId": 241,
    "serviceName": "softbank-2026-demo-1",
    "targetName": "aws"
  },
  "projectId": "38",
  "release": {
    "id": 120,
    "sourceSha": "b3ec1f7cb93693dc3e0f4736bb069ea4519b4d0e"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "softbank-2026-demo-1-75.likelion.uk"
  },
  "service": {
    "exposeContainerPort": true
  }
}
