{
  "containerPort": 8080,
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:3811477afcb2faeb509b9f09292023620504abd65b98478a056a63b8107dd351",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/6"
  },
  "iris": {
    "deploymentId": 17,
    "serviceName": "vars-e2e",
    "targetName": "aws"
  },
  "release": {
    "id": 15,
    "sourceSha": "446917d6b46febbe2b4f7927166a0cc501de667e"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "vars-e2e-6.likelion.uk"
  },
  "variables": {
    "encryptedData": {
      "E2E_EMPTY": "AgAHIuP5eNPCXThyeXXt0YxmaTpFmRuCtcS5RJdcm68IF1FtveWjX+ST1+PElZW9NdQ1S7cIlbTnOtlDnNYnLT90MgSyTLUwjLYT4AOkQ2BvojgIaCQbwWZPgY1kaO4D5SCzLMdQgSr+GLuQoGjlzp10pU47SStsylGxCg5OQlAowvi82qpr/dkaUGCtBI07obub0Il+naBsGOAooTIVzWZUW/qY74Y88ILEJEzSBgdMWDx+qaTuVil9KKRTCDyyEcahIxmjgFfqC8AvECtkYY44tBejmMJjz0f7XoPkiujFc3gpUeEcLqPxZ2FSkz+hCj+3bd3pX2RM9BTsQLjBfGgviF3r8ytfEyYhb7vVkyc0etDZVjEDg4mxMkH9jBW1/N+ZbGdjFnGmWMIB3aEi4hLWmhDeWAnWd00fpsQ3I6p+7OitCbCmDdw07fDok0qzx4BIOBN3hEpjXegCgg524oP+lzs6nSSwE8f++cn1dhd08usIUNLV4/omgXIL7/uW9fesRKrgqR1Xwm4QliQkgqcGpcjA5tTCTRn//nPTGAIsy1K7hJgRfUVc6BAUskkz5WFUMbPkRrWkjWrnzviAfg1TzzqsVisj7LATu4oR31miRijW2YEVvvSt6PdKc9SYkcard7151pwDe0uMC6iJqPwPBOX3mdVRUzbtHtpgsUHJhbaUkdSPrnaOSMO+qiAbhkk=",
      "E2E_MULTILINE": "AgAATIiWPvDx8VRpp0kdiSKwz+aV6FyxeU3OLEbTq5jRYXcYdd1s0bi/1YPCJv2hS7SfX5/e+DekY5GZMsOYWtm4hKZZD4fHXTcKVmFMkGk3ptFUtT9DnbLYNO0G8oilFY+l9iJPxUnPsAAE37TnoDEQinco15yACsXj9PZUOa9DV2d89iBHkFLzD//vZuEBqOzihfVFC7ie2zIV6qzFxi6ILamiOvt+DQCoysRrESNIZ2f0pXy/s2IPaps3FjEyY640PU5zUWgWvQ+0+i8VL9QvdEWrqud0Cedfdme0MDs8nKENgoSEwWfqHAueSVw8tA+NMpOV3Uf1JxfjjaxKh+Opdo1i/DJAGmRcJUZ77lP2oSa2qdm5/gKXeOm97J1wvYFNXHZ48VrmsqWKk6RBdBGT5EgmaG9Cxopv+jgjYKeJkhy11eCgQYiD8NWcLhD978FotitZWuCYct0KRYDFUpYTobOXnR0vHjpCXt/YWt/BsW/4NJMqROJrGTsxctA60OeeYJQmm08PUt/CZ+mJsRBf3ANrr9ttXLo3nid6gHx5+aXKLCLa7Ajv1cef4jDFYXWj1OfkhxKTY8md/qib9aPYoGlSvqjdYYwUwS1dq59bwAHVCIdROt8kng7ukJKjQ+Wsp3Pgy5l3JdvERruFaRlkGmwMVkzEt2WFuXSbJJdyBQJyUPicLVU6ZeTjVTfJlNIWgbfyu6dvPhCknUoKXB1pzyxmTWOgiuyGq6g=",
      "E2E_NEW": "AgBnSxMb1r7t9iNZNRD2QRC1vojojr3djVsT3B4EoxpYbMXoKjAomglk9qI0bHuFjPywciCWa2dwPsbqdUqe3xloZKQhbTot+fuigxv8Bb3wbAwnCnTpbvzxzACWeUA8xuznJxSh+CFR8V3QxgG8esct7l7APFIOVieYpi3BvEvfldyIgnMbXDf34rExlk6Seqaasc7apxy5tN7SeSnBcKHyGOq/tQx/ptFugPqZa4LOhyeC14pZ0fnCNYUc+S29yG43dpwU8aV+Uo4PXdL5sB7YSut+8iBA3eBaAZVT3oCYJGLsTaz3CK0jUjlC2jkpxiyI7g60DvflulE1BGcmGPHivV8Ce+WCXtZHOX79bHGAfF0vA0L3Z/o6+I3fjVThQxw3WqfgA/AJe0SIDW8HkCvDXzzcRjaXZ4skLx6kJxxiav36lPYfhOWZo2m6oGj1gt7912xd/mfKtUNAPqXxv6xhRVAAtL9f/E1ShT2SUfq7zSjwob3CYJBaAy/uef1Sxt8C5eUWNhKPTNOoawTgc0CgM8CaO7m1/CJbYgO2X1FfXNwCI3H3IEfGUWDgiMcGcQn2k1o9jJg67cU/whozGC2rZkvMVK8BtVIjlY/sn6dOouWSn7ABful3sbWyE/z8059mSpns138M65j8Vs9IG0Mbv3534kj7mUvdTSeiGHfz4ta8zBNPGXkVIANBhyDAK2HfDYNqm+Sslg==",
      "E2E_PLAIN": "AgACw3xIWK1LLnvqX2/mEQ5ZB7RZbzI3XMI5jXYqMnZ9aS9o14/O/NcqFbqZMB5Cg6ZJocWC2hQP1OQjPvSRU8yrdyl8avSgIPX+lgiq5PaXUrK4IfdNGhwK8DumW99C6xHRN51BQuGwBylT+PZi6E7khflPtOzTwZK+RvcQgMfONLxSD+kAFmOaiF0+rqlAv53498Q7OmxcxOJYGgLUO8r4IrxUPukxrpHNfiYGlNeEWmk8hyDdABISlFbBa9/lYDOcD9FaNsa/o4GnWs/3k3wQW181/x9kihkBXa1zYkwDOFCxCj4TVjRPOYaALspYQtf5GRqAqVi67Jy3YNCe6Jd3qyaTWLKf6t2a9oiCQFWi8aZqVO+dlT8C9qyli0FXGDvcPBAeJCt1sbTidOVz+nmLKsNocNrcss1bc1v0k7+Dj0ClbySpNV1DvY99cZvUTFTH4ZozO2kflIf7qijRh1iOZ93LHwlMpzFctHtWOVE0H1uSx8JvxKehQD7dh3RbQG4AyujS8H4QLVhsNvWynZI4fg0kNJfGSeuJGUUnMtOfz+3zH1qgW1aLIrq/PPMo7X/0GzsZtaD5WYmyqQH38DzUBB9aa3zoRKlch16HeAjx4ILMlocNJ86nXad4kQldUCOKrWhDuWW61RsjUXEVaikvVhby2TVfJOBLa0tofYSfq2hB0rqGBtkqLJ3R32+5truBlvwT1KNvBA=="
    },
    "name": "vars-r15"
  }
}
