{
  "containerPort": 8080,
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:3811477afcb2faeb509b9f09292023620504abd65b98478a056a63b8107dd351",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/6"
  },
  "iris": {
    "deploymentId": 18,
    "serviceName": "vars-e2e",
    "targetName": "aws"
  },
  "release": {
    "id": 17,
    "sourceSha": "446917d6b46febbe2b4f7927166a0cc501de667e"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "vars-e2e-6.likelion.uk"
  },
  "variables": {
    "encryptedData": {
      "E2E_EMPTY": "AgAmsHr9/8Ie4xMFSzVmpogh7Cpt1riwYgi3QPrVkY5UjM7H/phvMXfTVtRd3hLjYSx3Loxzzptx2i89ONLI2RQnvsx+eNT9RdnQXPTDCTmhxxCf791njmN0urYznzXO+a0V9nn0Kfc47K1JSwSEDK1uH4k2VdC9r45oBI4ES8ndCH2QcgKVHtpUngiYzDAZUfsqWfhMEM+J8l8cU2zNshkwYJdj32pPHvJojHb5xjhkK6DPNKaZI5Z8yT+Da3wwU6+y3MwNixt84W5Lx2kzWxRiSQmTVM5ubFj/Lyk+P/ZcahSigZK0SATtcK+dJBLah9nb/5WEHpcYKiSyZbHi+pyb00v9YIebGteGOmp+rVodDpCEPXtE9kJWWjKQfCWf3k3jWB5u/iYgvO9DbCI99PPtPiv25Wd/oRxWtHO/hgHZJyhLfDb0JbGERqX7R5/lPooyoPRKNa5v0qQxxrubt8dnmecnp1f2kEG2jItLJ/roGwKLhWkNiEDhVDTwH9urcAz2snNN0bz6jckx4M0SUhNx8AN+jemwONtiWM4cd6cvj3U7yX2Y8PuSkpNaaX1tXsVa2rtmmdd8+3owhY2PI95afzNI2yjMhdnPilYuR13e80ufTWOZ1ljo5fKmleUHaemny4/uUlBvj4OV6+JactqFSb2Xc/i18LlJwwTArSbAdHDDZ2/yDunfZveNH29wMho=",
      "E2E_KOREAN": "AgCXz24qRzWN0DZWZ8vzg6aifhP9XqmH16I+cny6mCPfmML54UB6zWXBdgTgqkGn1Dn0rHUkjlfeXYjhzSwVbC5VTOfhycMlniDH+bGkF+qQgaV/haE4jFYXR+7tj8tU1iSjCAW+wb5nRFDk8R7OGbj0dUrcE6KIGcvLd1rLtlGvCBsPrUhW+TvMKA7YywS1pzmDhXbyiqHy89tKnRxj4gGuUytPWaPbLZOFR64zEYfdO5Q4Iofl6RwaKMqUtIGYqcuUN62w4IPFgiJK46SpkCohsq3aoFdo00OP+2zleN1I93wy97EVe+/gjFQa1giCWYL7X1x7YvbXtJmvdY6qRVmD+/8NivKeBCfPKqOWrijRpLQdH/7/k4ERbO4UU+TNm9vMg54TN3BpcfZgYk93s9NQ4NuLsgeGH9PiNwCoogkb6PlLXaTBh+lZYVWi8hjXkHRdmEIrjbdeZSVEzz1Qhbtxu+3OnUSBxxtXIJva034b4NJIYd8ZWgVzP3Rjp67FW99y+7BRd4k7zcUYWkAX+CNSVXwmwiaBwtVYKVV6ipy1rCSFczm2Y6sjMFP95VCSw0baUB379XQYUc9XjtZXLz4Q8m2fUofq/PDnQPyfGDyP6iDopdBHeWEBkkHfKt2+hXfyU9ZZDymNo+h2whwaFgNmfg5KQ+WH+vKMeDsd0jH6EPgr+MaolDD8w9o81rxkPSOn5UfrkUr5apx5u72D",
      "E2E_MULTILINE": "AgAdoWYmfbCx363ATl5H0j1Avc9Scee9HUH1rVouXJ2lKlPVEC/ISE7T4PMP9MVMsNBT2t5h2NtmiUWn5iW/3DoO5Fh+djzHtXk0qnTTXqPWWbph3s/EHhl5+DC32oJjo+ChnFFG92Sf4Vu5eUK9j5m0intlCz3rhiu8h3d8Q1kwMOMAgcMxvnFcUeABaxNTRCCGGjCkQ3KC1ZJklJbc6UKuyJm6N1BfsApQA92lkWDlkyKw/bgzpHsvzHe+6Ob5QHxLcBaMe7X6hfP9WftOyH0osXoE3s4VelmKJi4t5+HvkItENw4wdNYRIuHDw4t8pEbRLWw38hfaL5jIYQFc0KJoEe5C8+b+JU4O6OAslCeznj3GdCabxDLN3wwzg4v7mJECvZc0V6p8vjiBqWEysLnvLciFCikLX3PHJ21XzZBcTyzGL2+RFXtabNF9lD+fK1KW0+7yrW+lycRilD9QfJwuUw3hwZJSpNbu9fvLsG5w/1tCThISOHS8LbX4VrDm+lmb0fu2DWYkHEcEX4pa4VG9N99YMCD/++kQoK24FrnaVJ2T1k+FO52IlXV7KMUYhtAWRh842k8YmSVrRRS+td2UkLwkNvpPj+/mdwKyi7cWO8hjKP36d9j5PizoC0FQj6+bmxg/thRy2RxpSc7KG+Y/eifqng6CNTu+DORtgtQai7PQ/G7DNlsuBave2MNpmGLGO/1V2iQ49U9Ol4t3iy20+Jp2CC/um1ze3IE=",
      "E2E_PLAIN": "AgCGbJUR671KEy/BrywDu7qtCrOj/n88k3LWRDqZI/VCxFOv5ZroGAug8AMwdwvIGCcxHzGmg5kzyb8Ih8letsOgGJKs+UxMJGTsSni8CcPN4xkYVoPiUSfgclRIHUhaIqAsQVf04WG0VgX6XaavSdInTttRKUxKN0IhMi2RuQaEL5jRahyhqWDwQvwC00EXlpa0oRA3Banx6HpLpnvnvyXVGOPNWzuMYKlk1WpIJVeVB7MyAdS9Vby4N6Ag8IXvH1DYrwMdmV69fsVuPkvveFcdgPD0vzmbvEwrSrShBSIV/AMpz4+XEf6R1xEo2h/o+i8LwvkakcxXCtVYrF/91pmAbnELW65Kjzb1NlZSKLWBEQKpz8jsRw4xsxBVDrTSeC5fCPqVfrQ7DnHZV5yYgjPMObP+oTf8+Y9e+0u8zpPLDxA7b+EdfRHaOl7e49uN378gd/3MZBBUcwFKiOI5QHPkF2wQE4nWBzgtnacZvdhHQic5QgHIt+4p3X3bxY4GLR1ZRhQNclPMkuGhDGX5xUcYsjkuloP+Na6ZL1jS5LX+twWwX5asuEZ5rxlynhByyDE+4/GhiLogEGtCxKdZdUvU82bFF56kpSLHpC7Tt6n9urWZQLpy2eZno+S5V0B5YetmP/RV/zUGxiqpjcPDzEtLrwTh9cP1SJHHwkGu3i7gt22gFaU3IuVnWMGSpPelD0QnOh/dYU2PZg=="
    },
    "name": "vars-r17"
  }
}
