{
  "containerPort": 8080,
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:3811477afcb2faeb509b9f09292023620504abd65b98478a056a63b8107dd351",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/6"
  },
  "iris": {
    "deploymentId": 14,
    "serviceName": "vars-e2e",
    "targetName": "aws"
  },
  "release": {
    "id": 14,
    "sourceSha": "446917d6b46febbe2b4f7927166a0cc501de667e"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "vars-e2e-6.likelion.uk"
  },
  "variables": {
    "encryptedData": {
      "E2E_EMPTY": "AgAgpYz58tjKZiNXxHgetwO4PaXyqaz3eyEHtudzo1UgdVGkmOKw6usXo6SBr/p1DCySfq5v4nuVdnQwSwE5fYNSVBo+3uzlLUhnTYhnXJLPNyhHKPNUpf3NyJ80XFZiLG5scCXbNZazsRgN0bdeR/UkgZAlKxEHHKYSOGYFYP39c/fvY7ebTWJvQpGjqwJ8VNmohnBqv1PHxWKj1Pxp4QKEPh5y+y3eudW+WJHMdMg11XzTXopExXCX7fis3beQ0fs/LI9TVSl3Ch5tpT5V1dAuPkpc+i1b2tm/YaWqSrJiQNeG0M9wDdC0oFSqe+y5hjHEbFIEJM20cO7yrFSsjkRqZ2Jni5R9xJG4EjR3EnecUzuTCIJ+CZUn4+Uycq4bBYOnt3Y8BRZcH1tX+7uI/4IhUCuAfJEGg3Qd1iD7K2C+nxcPTIaEe5ppMO8cZ47BdstQ2LrOpqoOOnAzczmbmSbFA6/8dlnV04vmQNVQhOhi0ngaV/HeoQVjL4WRKlI/I2+DYmCOGw6mchu12aqCTLxkdM9skJ9Vg3qB4HUeSPa7l+VjC9WXSNBC0EC7cBFDz2FpOY3WijidcoxXrYaBfkOq4KDSwToH0C3oXvom1XUmorja4JDm1XY3/fZsNzKG+C53wPlLw3tlOgRPyBwBZhWWBE5oMdnMGyi06UQP9f1UOT/e5QCOqn385S322NC7A6Q=",
      "E2E_KOREAN": "AgCb4Aob68128yWmLhYR4knYJqTMd7FCe/FAGSVelE+rjFWmDgDOuh4WwFqWvJR5CWfA3xfNWo6L2CeC5QG0wNRmI3D1ZfxuxdEODkNaJm0kh4nw1tu9MciRkIbzfTY0rrSB0niOvplwtS7n28SP1Rsb5gb4FZuE52HMSD/jqlwK2BLwWs+txjynxBoNYvRWF0gIDf4fYTYu90lQ6ULxgbRjda1sLwFLhFA2QcuvKpSqQQrxVB8Ioepl5ssBFtrEgp6JMixiKjPZHOFpPLQUYEU75PiQbOnFi5faTMOsvBHo8nqaAHDuiersx7smNdLt+59F4T1t1Z2GXDdse0Z1ivmKJfLyjaSL3k7yL0eJBF0OYJjLjSXSXpenI+/LakxWsGkgNF58OyucFLwl6z6SvBWiVMa/SN6cQYRtjq3EXgVzDsSOYsJeKl0KgJvor8K0Vu6/12VzANmW/fBG/AuRvrFjiKaxLn20A6cBZr1V2B/goBgl/kgNWLSsz+JRh0di0qaSeX9inluXty4NpKIj4NPkZpKrGZKyalVFV+Z92lNVCMn+w1fD+mqgxSCz197vQ6jiaBhz8pLWDwO4I8IaSHOnIC/6hpCNPvwdk1RfLo9LaxsTkyyL2wZQUQWW9R0ycWAgV8xD8XB5ho9Z78jVbFebKtLiIpUZQGJtCtdc9yvC/xtBKF50KEvMr0rKaAnntn6jaPC8pBjPHQxlPCr+",
      "E2E_MULTILINE": "AgBVtFpZR5ZyZR2wQ5rLYUM/nClPbiGTJh9R9RAfrraAv2Ui3vs1hlzGizquRp+V+6/QFIUBwHqx3KGiHISicWL251EP3h+bM1hn70/ocVcMua+vMt1awNMYgeiyIdGLJSu5nyAOf/ac+njnD19jElYuejetoEmlQKlFzVxFeGqErzFzjeWzQAObcYt4s8n4f1Q7Z6ElMdw0JaPMLuWeSs1H/kgnt6G7QvQ+TkYyo0PwNyJe8cvhpTtN5cTL3ALt4yA+iekw59ZBz7ZC7Qm4uOGqEo1bGeUCuKQF5pWDaXDhEKWuUo1B8igNmappdXGTDA1RslGNL3KOxOGwcee+b0iSlhatJdb84sy0am2vncPitUUxd+6T+6Fjf+OqOwcyfSj07Nop8aQ8KwF3T+ooKSj3J4umRUkbgkbvmTDsWbEPbiEnAz6B4HiMrOH7KM+JXw0fEIfiDjbu+s66pfv9Swu9SI+YP8r3Mi4hM8bfPZvPcqrb4ppVYstaXGPatyqBgr3UJAy60244aTd6BInf65cC9YwujoRfb3RkJ0vqOfbHTx1xPRY/lozx04ol8jqDZT+RsBP1nYmgTy02rkO8tzShVjjWL5t6KIgl3JDktvYEkehphXM5X1d6mDMrRZRntclN9wWw1wHGuYIDN5mOk6MbSsdib4Lb59OHICnHYa+IEC/YKGS6BipYDOCM3jXhWl/k27KquHge1wb2tbUFDuYC1Flb88ZDcSYzKVk=",
      "E2E_PLAIN": "AgCuXUw7b1gclZdZcFXymID+EOfoTfUghb/in2HVwPHW9ynS/KUXPav4gSinLzDUF2d3D/ULvddckvP4I6iV7R5J1l9VTzQYpNwFH7E+rbTHe1eJPSG4aXDeHEZm2aA29KZSVdUBgPJmPK1RpsFaYqYTMFjdT8RVM6rPmtlSdDItRFCy8LWsJsGO0belqcvRJqxKFuGO17hZGkIKPG0MKElGRZ1tftZIhtF/5pdFQOzSoq1s90Ai+5xxtaSe2JT40q9EOPVLMLdKLNOwMCWAh8DNpAKGCQtjWqUqbE5m3Ms3NSbM5eU6Pkc6ozhI/SO8lMyfn1btIaXkp4/ZjVRXd/Aa+rGL8ge0cBc/a56ki8hdP1zC2isG3VthRz8Xv6Kx2w182krEtWrffmFx1fKCOg+n1bEyvrfMaApOXGUJCEsk/rVeIZIvwZ71Ay2oc9WwFMVeIurKrPgQceV84PTX2dFOoQMk1UxdCl+TFGh5QfQSQD0Px0T4uBjAPHZ+oJONMIuEIwhXGFFQ3/oOCh8Yj4GTEQKPk2iutwkxMxnuIvoOeccYigEhlBEP6drx9rfVB1I+2+PsiRJWRlvL686Sg//hdyoCGZjDAWZEAhsEWzcw9VzlVU2vJFVLBzHxiZ0iRnHhnLIRz8+LUQRNT63wlDVQ/NCFqHm9hYKhVyaax5MEIGdZ4b1M3i26dXhaUsU5jLSf5tKCIVev/Q=="
    },
    "name": "vars-r14"
  }
}
