{
  "containerPort": 8080,
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:1c2cc7d21bceaec2ff8942d5a5457a67aeb8a6d939161efc87b6e25d089c9cd8",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/28"
  },
  "iris": {
    "deploymentId": 100,
    "serviceName": "portpolio-production2",
    "targetName": "onprem"
  },
  "release": {
    "id": 44,
    "sourceSha": "f54230346fbfca4e34ae2cdd1a370217611d2191"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "portpolio-production2-28.internal.likelion.uk"
  }
}
