{
  "database": {
    "engine": "mongodb",
    "image": "docker.io/library/mongo:7@sha256:1f995ad6fdb93244a1addab1b58f934a0bc2f5643c38e02f5e9d7f0c7d227a7b",
    "port": 27017,
    "storage": "5Gi"
  },
  "iris": {
    "deploymentId": 165,
    "serviceName": "mongodb",
    "targetName": "aws"
  },
  "projectId": "28",
  "release": {
    "id": 80
  },
  "replicas": 1,
  "variables": {
    "encryptedData": {
      "MONGO_INITDB_DATABASE": "AgCKsegTwnOxuhVWzYi/uAeGEjVzDzHrblW5LXZe8sagI37YNoDHDNaoUxTUgugtEAn9TS99pXhKEuClhLFZ07regMYedza/ugguoFp3NmJBR7jEwUp1ZzOLtjJt24wUuuCJ+sOJqlB+uWL8BHE9TuDd12Z+aCUndk31AbVDxYKQFGUUe+HWVbf/TMvUJoyb9KcGGJIg0axLJhdPnIEjves7Tv6MY3Bbm2C3lTvmRdsvFuZuhK62ykbBCF0QGJipecLikzOUSn17+sddxnXjy8bveS7QtvPY07+BBQvwCo68OrOvGwRShk3j/QsfCSfeends5UtjYRzJJCdMr6FIx9KEqKYUiR4SI9+OznxPJFaR1jxYxAoo9rMr5YsnOtFR/j0aNrydRF1hjlih9FX7YW8/7sVG9Z7XlCOpbR5yA7EUCKb1g7SfWmFk3qLLraWwpTYmr4OKXcMl1yJgOqy8pf/WYUFonngRP3Nj4qMh2eIKGKxiE1kMojn7mMe++9rPDnP7x+PMfyR7nsPErfa76BKbotats1NTkgpomBb4cY1L8pHeWaNwYUyjY1qcyw9tobCfz2/0JndwP3MFV0VhagKf02P0d2hvG0lqco6ZBoJdp/qw848xsuyteQpNAg2BBj9EvRWBHw4YwB+60OCRsCz0eugrJJZXzysNYuBWTyqb05PNMk6cjsdppXnxWxUJ7iQr3jk=",
      "MONGO_INITDB_ROOT_PASSWORD": "AgCLaJFHOqXBEKf7ybohKXRwuyJ7HqT4NoINi2zpTH8VvIxnPSJenX3scSATj2O5Hkizbxxk44O+cN8k04gU+2hAesPidhmqueXmGiTrfWqZeL5ICZ+zNF5ls9Qkqa7JgbkKrYmG1ZpUFK7X8hUM63MPznxYrkLId7/tVtvKqzbfjuL81OyN4iUmKwP8xYe24NBT4XwBlVEKPIVfp5H31qqfV6pmnbbvCcdeyomq91gUbR983JVj6lOw20WMEfX/971cATFnylY802KFF95hAOkcHEmLICLC5g9ozRf6zmKR7Dcd5IM6CFPLjUVs++BjPKrU1Qt2bRDR76MeMZPXQ6JFjtJ5WG5Qffhy1cItJPnMdHR/uF+Gb6G7qnxmi+9dAGXiYfQr6p3629zUoS6BAsFTA1eddb+MWa2ce09Ei6EUyXnufRKhhOv7mHEtZYb4K1LpsIkXqWmecefEVsBiufOI7Wj48qq7UTq0bCg9Xk97CCG2q4JkMsP9ILliLV8BnJq2V+Ay6LKhSxQUslmUfwTxm76UY0JkLfStnZIuy31efo0/Z0eD4a6MmhG1eOlmNfwLEvnF4rO1Y1xEF99RYAZM5nEl3bZ/EPR+RkjuSBBZxanUdddlSyCk0TuBkU/EdefCo+dnY3Y4iN1SgZ32zTR/tmhrE5VZPSz5+5DOgH1TztKkuADlvXyKtdm5pLxbxzLuEjjbl+48Uxtw+9u5ldh8L8h6Hksrfd4kx9KQVnwQrg==",
      "MONGO_INITDB_ROOT_USERNAME": "AgBzrqD5t2LUwrAnVPMcqk66XtMp4bOew89mhmUTEKrQ6qkXZTNybLq1sSKyB4UVpjFKvzkxl9OOWzhbvRL4YXxdN0XonYGxJaiWlQla3/OFRL5e7mCsrA1mjdrGaqkmrrNm0oMEsRjWRvkR+4ZH7WQnixqIN4mm95gS4Hv5dlaETcBabypK97zDiQUMkdK/ZZLU8x6a0BCA6y5BFSMpWkKLikqdh9ZC3yAQJOy6Ksvxoud5Eb/tu4Vw+yNpfzWZAUjIvHL44aY19qYDup72X2GChzl9jX5hXpRe2QcdfWdEYcDBzrBcpm7R9N73IJRmH4e3DsXXVU6xvDAgl7g3fRpS4B5oCTTn9MdUEDB5+DOLsPWI0fy3pBRvSz/shPoj4weIoGNyYEwDKS/uBTspKFn024Tym9cYY9wjqRkxr1nkOIquxOOjmgN7GQoPcPZSsCeFY6m3ttQDlOcHICyGnA52kalEzU91ruuopZ+mBUDynrA8Tv6nOav2SUr/jyessUWBalohR8SijdIz57e3S8DT6XiRJMCNx7ZAMEzSR8eFTfUMAN50I9e6Fgf27AIH0B7BtXdH+xeIvj2IFZ6/+LvvfxJFjTefAlSfF32umBWE8idkRndJQkcQaGZHgKgaDLjB8KK8I4uYsvm9gY8rYQvlsuQ6UWB6R9EwY5fMvilc/balkxWYCPwTQTcj9Ow6iHpcOug="
    },
    "name": "vars-r80"
  },
  "workload": {
    "kind": "database"
  }
}
