{
  "containerPort": 8080,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:a3142dc382f85a884ea39bacf85aa6e2726e508e33a50544dd4cb9ef2168a7b2",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/34"
  },
  "iris": {
    "deploymentId": 116,
    "serviceName": "softbank-2026-demo-2",
    "targetName": "aws"
  },
  "release": {
    "id": 58,
    "sourceSha": "ec436b366a0bdea1874af81e6bdd49e02d7bf281"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "softbank-2026-demo-2-34.likelion.uk"
  }
}
