{
  "containerPort": 8080,
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:515ba553c7784a25998353aadc4992b567104b04d1af548a2958c84c770e4b73",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/33"
  },
  "iris": {
    "deploymentId": 115,
    "serviceName": "softbank-2026-demo-2",
    "targetName": "onprem"
  },
  "release": {
    "id": 57,
    "sourceSha": "ec436b366a0bdea1874af81e6bdd49e02d7bf281"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "softbank-2026-demo-2-33.internal.likelion.uk"
  }
}
