{
  "containerPort": 8080,
  "health": {
    "path": "/health",
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:c00c3ca7fc5015a48423749d2243f7861665586c7634dd08216bdef0af1a56dd",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/16"
  },
  "iris": {
    "deploymentId": 34,
    "serviceName": "fix-e2e-cb0b72-docker",
    "targetName": "aws"
  },
  "release": {
    "id": 26,
    "sourceSha": "1c283a66198edbc2a07ac0ee1168c8034aabbef2"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "fix-e2e-cb0b72-docker-16.likelion.uk"
  }
}
