{
  "containerPort": 8080,
  "health": {
    "path": "/health",
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:4437a362fc358d11e2acc118c9d086cb012eadd7e8c0a4da2ea010358d22e07f",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/16"
  },
  "iris": {
    "deploymentId": 30,
    "serviceName": "fix-e2e-cb0b72-docker",
    "targetName": "aws"
  },
  "release": {
    "id": 23,
    "sourceSha": "1c283a66198edbc2a07ac0ee1168c8034aabbef2"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "fix-e2e-cb0b72-docker-16.likelion.uk"
  }
}
