{
  "containerPort": 8080,
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:aebb78a6f96de543da9288901bf11a1d9bb912f21f16a4c0cff99b955b948dcc",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/16"
  },
  "iris": {
    "deploymentId": 28,
    "serviceName": "fix-e2e-cb0b72-docker",
    "targetName": "aws"
  },
  "release": {
    "id": 22,
    "sourceSha": "4f9200e2632e09df9476a56402a5a35e98b1d5a3"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "fix-e2e-cb0b72-docker-16.likelion.uk"
  }
}
