{
  "database": {
    "engine": "postgres",
    "image": "docker.io/library/postgres:16-alpine@sha256:721873c34ceb9f8d8fc265984940dc982404c105f19ad51be9fdc5970a6080ea",
    "port": 5432,
    "storage": "1Gi"
  },
  "iris": {
    "deploymentId": 237,
    "serviceName": "demo-postgres",
    "targetName": "aws"
  },
  "projectId": "49",
  "release": {
    "id": 116
  },
  "replicas": 1,
  "variables": {
    "encryptedData": {
      "POSTGRES_DB": "AgAyzBxdJMAuuey6sYcUcrLuYuxAAccqwBv3qPeMS9LrHxCEiVjtdKuVGodH3jpVfdV1bNZv1m0VAx3H3iQJrGCIVbVZt2B3C+6YmmrHxxXMlxTEC4aZ1lMDN05LapkCqk9zyx2oMFyQovEENmwTO9Eq0NOoYXRyPAgs0lplCuI1dnczzMPI3jzp513zuYJWCSZOfBxKe8kpXpPhGu03g2grCYJbbS7D3jqMHcfGLNAszOmIIJfnR91DcUpY2diBXO9QQClvSRlnl6p3JGwPcHUMV8XZ3cV5ZQG+M9DBwMeaWlBdBeKSvL+KPiB7yKqAvCL5tD2hUxyFd8z4yUxKPJbo0C91Ikb1JFl3P1+2R2+USJV5GmI5ritcCIuJvrrjh10iqrQ2O2kJzBCtVvrGYWuh4cIOOZTrX75T2i3v8YtkCRTc8//Eg9qAJfdO1C/MwgAgPHfBzWXVhCVOW2TMAQfE25OB51Z6/yNUKZaVvccbfsRODTOTUGoaW2TER+WVliRAc6M0ZovyDOMcjTECTC+hFgcd5GtWdftdBc+O763coKHFTn8wPFmw2QSytPYGsCkyga3ae1SfM7TXV2qx1SIIAYIPBu4MQQ7ln5vqgUkr7UEIbyIcF2XfFDw32ozHz8tgVbYUBJRmZ670Beg21HK6sJhADFrA8q5BsKDuMpiSCzK5YiPDqZ2N6PKjD8ubpHwSUWc=",
      "POSTGRES_PASSWORD": "AgAIMwg996ijnN/6paZGCIrksv1nQKR71rjQC15Wgl4sqCgdUyNyN4+5gJnzu84CsjYEDASBhbDjy5MSnSblrngftyJV1sLqkjCWtNkcMBiIXTetM+CJLyOuql3FBIBVM9ZisOZtru+lo4sGZ45NqE8MDU70dTIzjJuycH43+1eUzCZozvPjUgFK6pGqY6yOm3UUiI0r5CrYG+bJE6pe3SfmbPd/b+MJPV0f+GfBbAOZhUXXvQ/Pz/IjfPHtvwRdQD4yXPYZ2jZZzJ4d3RBMZzx9i9LMjfuOfLzIGngM/6PxQQ5aqX5+OcTrJQCxAAaUdRr3OZF9Y49fQQJknzRsCkF85IfpGhxkwJZOGVlnLl/5TFd3IILWwddNu7BOuTRcCNgrVDX5zeBSkmURxAtv9Fqk6IwHIDnP/P/64xnL4ChCpnP1nQWEkPny9du7D1V21BAql5g/vFoEucUqtF+pgNAHrVCT1WuGkEpmffRCVjnbVIW7UcoN2kN39usMMrhHDVB+NxbzFD87aSTsRa4oM53VO4ORAdhUrIo9HrEY9YVFEFEfQor7LsIGHxEzzYm1vCOcJtBvGd6x7sgm0pXSXykgWHOlTyBZviOUk8cUdSlRKvtdA07vbzqYFR9GLMo/i16l/UgvQZLBzBSNu8q3EISDAzZtHjT2r+H1jhufnafsJ5NzoXLn7d/IdDhzRLrztDPi6Ql+IxTFKLQDigMpLINRF1Gztr41s5KVcIYb1axCIg==",
      "POSTGRES_USER": "AgCsJgYFKt9PKa3Am6XkkbDT+c2uj272R1zQ+0WCOZDTsSzHUeyKSy2IpAuIv6gRHlAJNpbeUjZ2akdM87X1Uv7i/H5JK58QdO8PuOvh6MLPbfu4nBds7iD5LrquuI3+O8RCE28qv8e8wfF9tETAfc7arE0zMA9El4tghvPrr2b0YASj/iyCvEkrya/ILGlhZv9a3Lte1zbliyDXXzbX0ZOZxB1Nc0YFXP1HLNPWRabEOaz3n3T56y2d0zftQhB3GtRMRgIxqwjKh4GMbbOjVYCJiHymEmQ85N7cfXdHCNsetTaxZ0qmUn7px8DUdA5Vx1eSq33DJPgfwJ6DlIZhv2TyzLjDPpymGUJtovG4NFZzKF1sig4+xdgRxOs+3nWF755QSye20FcA+E3akC3bwOIB9qk7x2m5NxHQUxRsRf8wfopCd9mspLz6yD6M/Hv/qwFajSYcpe/kMT4ueUL88YVqAbv5VIUpigXvtEcZVVzIS6KHLpvN3YKNMy3nBVubxQijvi/XLjEVujHNxoWZQmpaweACrGwUbFNpClStkYHkeJm3j7EO8eZg4b95ZvhocwlquEB+6Ja5x4EOt44tTUwYAGDU0vTNY2f2YULoVZamAEUGpBP7B3I7JSyuGitHI21AlYel9uKycppnCKiFNyOnLOsNVVQisjYgan0CfkzZum3TwZlJgH/ru0qzsbOWFhmSToU="
    },
    "name": "vars-r116"
  },
  "workload": {
    "kind": "database"
  }
}
