{
  "containerPort": 8080,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:f819cfe78009d57ca6384aa0fe25f969dfd7f2afebfbbe93fa801c6e4211677b",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/1"
  },
  "iris": {
    "deploymentId": 121,
    "serviceName": "railway-deploy-demo",
    "targetName": "aws"
  },
  "release": {
    "id": 61
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "railway-deploy-demo-1.likelion.uk"
  }
}
