{
  "containerPort": 4000,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "hostAliases": [
    {
      "name": "mongo",
      "target": "app.svc-48.svc.cluster.local"
    }
  ],
  "image": {
    "digest": "sha256:16dfb838a799dee60a628b45654ce52d1c6d2e11afa2c6ec4f7a47593c06d5ec",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/49"
  },
  "iris": {
    "deploymentId": 152,
    "serviceName": "app",
    "targetName": "aws"
  },
  "projectId": "21",
  "release": {
    "id": 84,
    "sourceSha": "03c736bab48fa2f9e24ed7950f0e27c11138e877"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "app-49.likelion.uk"
  },
  "service": {
    "exposeContainerPort": true
  },
  "variables": {
    "encryptedData": {
      "MONGO_APP_PASSWORD": "AgBslUnqyQtx9r1vwjsDfFikNCngz5ieVoq7ZaUj4aaEeUOy1ZAb191/NBW8DALmHqs3pMiksIihinhf537bRlSuJqVaLTJDpz/rX8q6BVfpZaKJnaIxmB9m/LyI/VJlEFDDFNzCD1X5CcTR4cEbFSGXTMcljWIP0m8LkQFoFuk4jdtSMpIooYGpVDLtyFVrZqmjloW0c4bmhAZ8M1Fbb36pbyHHBox1IRCwcOReKb0KmoqIS2FE0Y+ovtqaxHJE8jyglwOjA5mR9xKkwme1w648ZGs7BwZDIQIrRPOJIZyticOgDQFDWZwofQzrAQFu7E4d2x1nynZUO0jKkerd2ggOB4WN+5XImDGt8cOIe8LmbD6yAZ/xXuaGlw1T4zrQW9+EyAr76apJJm0CN+9zzeygMCmT5m1VPZ1/O+srjbTwRMTxIHEGxDFWPtTltgSyqAI5+K4plDrpq0P2kR+GzTqilTg3wkb5nT4hKLRbkeafCIv0cBjO6K+B0u1RyZlwYMtZLk+fGOGsg4XNiKcqWJOBNzYtZ/eIwhHtKy4cidaxEgXKfUgBarbCbVKntS0X7DjiMqXB16CGN7+5RNAq1N+rc6KMORSkrMaNvJ3cfZur9kLuS7r+lReljTmwraMkv3o6gd94vDwXPqTaNQyYx3kWnqiVirp/y0g5LKIyb+OezRQcjcr6BH4tgMBNdH2vg6EEtLQswfjeCqU7iEiOc+A3YmM/2vrv+wpx4pdmkqfAkhz5Zx63oBzWwKW05I1A28iafslQvP054M6ko7MNj5gg",
      "MONGO_URI": "AgAq5ybx95F4KZgvGHszA3zrQWtXZ0Kyg0BfjmMuTR+HNCm36AHo3P7AMzFTcJ9byHhijYoVwmp1m7/UtqqO90dWAgOp/v+CYQ+n/VLIOSifFuvwjA3UcfrkqmRMalnNqvcwsojTuh3bz3+U/SF16U/yWLOtwCrLIe/FO5gh4+/Hn4UbJlZIISqLebW0BHaZBDEdFNgm7op+rpbDSGXPgIV12L88KMSjICCCbiTCdOLs0uqdmmwmMNhMWO7A6PeiA0VVtkskOBG9B3dmJ2h4I+zi4FsprMmIis5XOAhLZyjvJ5Xe7Zc8f//c/F/jCUX6e7XZbiIWhrrHRvUZ4khsdOCIL0vcn74t66daoEysJKMMkUNH9E60K78bymyQbmxLc4jan0aslgiu6k6d5/jViU7bfbsH5tFgBt449+zPxNm/rJlyzZiFRJLFYr/8IiAnNNVcdP3nrdZdJfU5gbhDMxm5nQQnqYqK9cAcrg+oV0Dx15r41PNp9qOl3pvPLDkOSaSUtlO1GNv0gui+WlgE3zHVnAnASDnOR/3iMe8Am66tqVYz0lw24d6hPlJteyD57rySO1gk7D1FHWrIloFKpaTeUQBsc6mLpJBxxQ+vJxE94VFmbnCUJwKtHzQaQiBFmTdJBNZ8o26GnDLQ/bXFhMRDeUU7rUQbvA+8bfv/I7CLbgS34NAFtij3XTh8Ka503jPmJixAutqgIXmKKbgaTqHBYtba9t6e+sEUIL09soEhrXDM2AZpcygNMIUm4/P8kznNSZdj6xYJM+60Z6tipAceqLFW17fJxjQbAf/qCR8G8PVAAtMhHnIk77K3N90k0Uyo79kIRcipz4LLFXU5544s5AdLlZjGidiJsPFg2JfqkHRK0MyYMpTmllwZPeNRbkg=",
      "SESSION_SECRET": "AgCiOGwhtJR1pBcQ0hfSw7tU5Dibi9h/fdQxttNWEroTxV7Q2a0ssUkeKM513DbJ6kn/Jz0e4/AmSawomHxVB6PyZOeDdL34Imt/Q64A7x0ZMUpol63DKDxYMx1RjNitHB5JYz/UZ7N+fULpmRvdgOTRzWaHEqlEu9/CvvlZJV8wrYv9IAJ0L/H4dskGYRo9oeXwMkqBApRTB5rET2lrNxYqdtlVQ8fR9WkWoHCpYeOiNKTfhqk69kCl7tKCR+rhKSGjopA5GF/Ph+HgnzqSv7GewrRTsu/I3L4mBwf/kcheXpOt1Ehi3dolTpyVZTpYW0HcmwRIcfiPqX92U5Mcc07utqt+gH6K9/h1TslZapEjQpNEjXLp125GQYoefPxBmzOrgvYwLj2as8KLlpte2OBdgqDLERNzh3lCr9C4K4KSpNjB18UQgASEJtC88G4sxKro3xNfMaBFW5eBFdRemn4MmZzQEkfqnCtX/hLFSLkvpiAFZ/nX7hjWjq1jXzg7bWz3Zwu1BbdiJpsFuN0mwckPYusHpWJaE7mp0O+h2USDj3vfufSn6qpba1Xf4INQxuy1ed8pmgEKqWol+UyR/cvpwOWJTPjCtcP9BY5iGtBpM1CjS3MPrkKJRGeaYVj7C9sXvogOMtl0gpbjaprx+Syyf/sFdncHsnUpj13eEkZH0iVAVpnkSUSnfARBKo5pPtw9CC+3uUugFC+cwRlonsntHh/zLlSauxWAuE1HAgDp/JxHuGMb5DOyUaLsLu7GTylJYtEJ2TL99z27GWeMNzbh"
    },
    "name": "vars-r84"
  }
}
