{
  "containerPort": 4000,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "hostAliases": [
    {
      "name": "mongo",
      "target": "app.svc-48.svc.cluster.local"
    }
  ],
  "image": {
    "digest": "sha256:72cb2a043787dbfbb4113f73fb747a7aa87c1c5fe855a39ea60d9927dbc601ad",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/49"
  },
  "iris": {
    "deploymentId": 177,
    "serviceName": "app",
    "targetName": "aws"
  },
  "projectId": "21",
  "release": {
    "id": 93,
    "sourceSha": "42568f377943e77ee01fdda30ed833d96f9defe9"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "app-49.likelion.uk"
  },
  "service": {
    "exposeContainerPort": true
  },
  "variables": {
    "encryptedData": {
      "MONGO_APP_PASSWORD": "AgBXzJlrp049Pw5zsYaqFyk0xPSW84MOVbCJkAKI7Gpf21ZM8Sy0+qCrCcyxY9PiyNCSE9IXngGr+0Esji4JTjS99slQn8DpWX8OmExOjwAWRDWOleL292SO5KNKbVF65c4LzAynoBao/ldSByB3BN4zZxppksApw40np5YSdx2Xz8H9gx0FDCJKNl7nSmQIW9/4nhFJx95Zzgl8KEWkHfpd+1rXSvWmuVGbL4BLJPO70jV/jFaMaxScO8Fi7lzS8JT83CCW+d1bRUQrtB+b+m1wnfYnTZUsNyRxJfoSpC/J14UHiCIkavG0nDMayYWLrl5f8wzqq48ynyjVkHF9LNblVb5j5zXWd/CDSItyvwc1sFof9/lc48OpX93GUuVtHeRGsZ5nK+72AeTVrGImtBaIikM/HC8xhc3k+C363CIKpa5DJBOMFZ+AxVS1wPYym5uprL7hRV2AnTjdXkcEEKSwm3QJiWELRpyRjPqRf+uHyLdjUjIkPeQJW1xoHEbhObV5vpl3+Ey1CAJLIY2R+CJRvoAS3ccaUfcXcjFZRrpscdqcEUTbODN/2NLfKtdVp5LB5URWYAPN4C+yjyHTXr1GY+P70KyUOl6OJNaztwpjMUflR0fs024FaBlPblPXlao6UMVXFEqGuP4RV+a8D/6lChbMKB9mx1fkZaHYJ77AektRHrxLDDMZqMXNCYlq5tYQNzGNkku4JJ4JZkD+6Fswi6/5skiyqQ8YEkiTQHjUeopF/eWf31Cvtkq37addjG6uBP7WOWMyV3daCH+hjA4U",
      "MONGO_URI": "AgBUgrBqZIkBVRokW43E3/arc35IxOJBCkeLVVwW4FHQIxsE4ICeWOXs1zxdMrAf27c8FE8dUJ2WJ8qcNtss1z3GYHBEhHmjdqO/0JBt0qKbQw7How9QJLI4L27WpwTII4x4oRJcfiRnUFCkWp+JCE8ZJRfv8D6OjxzR8u/JsRsGX8SOpgCvm0s0pzpWwqOimLbxJKcLgBk8fDtf0XUppE29szAC+SqbwHoiaOpx+BuUf2UCfx02jF+60e0/K0udXOLIU5b+0+7+v4GxxpN7sekKjlp6WAMmr0uglWzVorRcaIYkPe1UupAXEi+qkBntHB1Yaj029QnHACv23r47iXeerHhl8b2jm/ryIBc1M5Op6ErUAWkuLYIgE10+CNAN7Ha9n/P1Zx+sLL6P5m0DI/FtKlUecHskSqkwnY/LED+r6NLa2EWBLXOIxaG84q4cU4njXPO6cPVv/FoC5wga/PO69jj5OB7MCc9IBgtRqDvfd0JZ+ZHVMm+hIqFIbX2PlL77YjoYWZrZsIBKNfIJgDV27ZLGPV3ZHOzCKvSztyl2zP4mXtbWmZ14c8UkW1BPaBwZStjL1+H11MFSb7uH9sj4b33UcldbvNhd3dblxYsvdofxq43ytimLusKWJh/6wa8GOHwaauh+w4mk8dZflOFR407TnZruKre8HJnPQKKzhzXLh0l9zsOVBL38hBrNlBkTxjKb74P8SWB+qIvnjSQveTY1Sw59c7o5M+mqTWRm2xX7Llz1C/Rb33TouzCvS8PGfFwX1kTI+78ekBzChBxiFVZ/65vmrhIRTrc5ZILTz9mIzLaHmuN2qycwgQz0rtRpYfUjXHC5A/S3+CpEVchSvmajWfHiyWLuLTTEKN8YU70jDjQin5NNoPWloNFAx/w=",
      "SESSION_SECRET": "AgCj4VRmlk/GqAw3CvLFzgp7M5/A6sDXo6wFexNKf0A1jTmVXGIjg6FPXXFmDzl3jr2jgNyoTd1+q33vJOTthl8FK9gbIE+pNNFvH3Jp1VDw0XlUwAjkqqWSqBwNfue9wqwPukoz5mi74G0EssGMAFSeENOzyC4cocJ3A4B26pnd73p4Fdqlk4owwoQFIMUJXurgPtvU66DPIBa2kLH1r0oRMBC2SE2J3hVZapW22wopG8oy1G/q5ipTQjpwv/Us8zQ6zD3su09F4TfQiTPnIwF2fOgihYsXCyZCJRTh6ZCYmXNRItwDldkx5m7YFeGMxYsBv64KgwqryujZtAnS4IEZf4MIQsc7NpjjwSdFVMw8k4x9o2Q3I4OxNQwS/SI3ycXtnmszAAofBUEyTSda1SlDsdYB1TGcAF/ReV3a7q4DhtJIKTzbhipO75TLcOEL04g233GnKCIDIgLx2VJwxVWAlglxmMx4zTwc0mhxtV4uEnewIu+SiOXFci0q9MnNhZctZilFVKSb4SSdT1V3vfaNFFFLdqkYl86Zw60juS7KBxupNVEa4ooMnnlPyXfDXc4Eg4GbcWLKoyeUeeip8U4OfE+dGi6RKRRFeXTNIInc+5bc6j5fdOGoRTRQUT+fT4VIwa/RSe+T1B3T5aPRL5fMfGCwJgVMCOi+8BNn4VXRgawNVyX3qEZhChnrjTroPKGkpWqVVv6/kVF1p+V7sY5soNm6rttXW4Edpz4v5FoxRAdp5qPSvalNVVyQiCdbtXpE+jSqLKAv+8Ag6mP6+t1c"
    },
    "name": "vars-r93"
  }
}
