{
  "containerPort": 3000,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "hostAliases": [
    {
      "name": "postgres",
      "target": "app.svc-64.svc.cluster.local"
    }
  ],
  "image": {
    "digest": "sha256:649c17c177690fbea299c4e39e13b44340ae18b59ef34222f18ef7d03988a0fb",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/65"
  },
  "iris": {
    "deploymentId": 220,
    "serviceName": "api",
    "targetName": "aws"
  },
  "projectId": "37",
  "release": {
    "id": 106,
    "sourceSha": "ad7ef4001b734afd4e1a1213c29a6c6e939097ed"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "api-65.likelion.uk"
  },
  "service": {
    "exposeContainerPort": true
  },
  "variables": {
    "encryptedData": {
      "DATABASE_URL": "AgChanel4rOpyfhM3dTOday2dTaH2NRCjBdSmORh/z85J/yo+PBf8y+tYazfLrdPMcbqnGi3/SHW82SZ0wlwQcNEJkx6LfpsQPuU6RFk3F7Yf7rqP4aEFXMcsJC1Teavpvg6xT8FzcyqO+20wHan5UBOZbm8caFs4fm1T7d9dqGKWOV+vvdnFUtlSuNzpP51Q1AJM0DIGwzpwfInePbowPbwoUJf0s4vhS4ZdA06QpIuBLNhxjod/+hAzU1AtFCw26UOKuUdklokhFGc5kuivY4/ziDcwP+tdjvAb5Ss8B5tTR7aFugcQnAj1rRjkoIKGhzTRHN2Ix/9n7Re/LODho9INxVxffxNishVh+lMTP/06lx4oMokeN675aZIqIsGCxL5x3aEA0vs5SagdQghmi8enTv/04xxqDfmfTQOJTLetI6450wjaYZiCAhep6RHFy/HdsDCkn3xs6x/uVw/6EG7+EVFNMI060qG+OnEXgszNBuiZc4FjPASohnpZWGE0k4WIbmyx1jEVAvfocVokpve1A8HnlfrtjqdRAT8l8wIS+GqbJZ6HCsxwQDcxxBngF4aY8aBUuu8X8UwjFz0pw01tyPBlE4uTAo3WeM9LnMgaM8SB7qZy10we+zT5y53exIl1zL6NC7Qdwgzz9JVlfsko9myutdO7odIUYqK+AW/GI7X06MzKo5/y/nnhzEDwLXsQ8TkCI7DD0jEY0O+5ygrXl2sjKbjflG7p61UPJI6Zs2EjlE2gFvUFC4sJXN6ekx58jQyoyuSme9cGPKt9vYEQIUV4rBYljsdwt/CErXu637Shn+lBOA="
    },
    "name": "vars-r106"
  }
}
