{
  "containerPort": 3000,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "hostAliases": [
    {
      "name": "postgres",
      "target": "app.svc-64.svc.cluster.local"
    }
  ],
  "image": {
    "digest": "sha256:daa4060c05b726ea45e98562490793b1fac1a81b46b8f99e3e38f9afa5bff8c7",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/65"
  },
  "iris": {
    "deploymentId": 223,
    "serviceName": "api",
    "targetName": "aws"
  },
  "projectId": "37",
  "release": {
    "id": 109,
    "sourceSha": "ad7ef4001b734afd4e1a1213c29a6c6e939097ed"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "api-65.likelion.uk"
  },
  "service": {
    "exposeContainerPort": true
  },
  "variables": {
    "encryptedData": {
      "DATABASE_URL": "AgAGv70xejYXsoaDg8iXC55I6ooMK3V4VkpTu+Zm+ccWAV5TnMBits0rtJTj7hL3N18eMMhE85SgISak2IDbJByLnNlCwJtObspRbtVGgi5NqeGm0XfUEs+u7NN+NOAeshpSqODAMu26kn8ZJEhknteDsBRr3KxiNn0SMrmHiTZA0qx7k7jyCzTEenyMvaOKuYlXZY5oCn8uME1GNKMGOvTTZ7VYsW/T2RFLJuVxse+Mm9pblECBnvPAp/+qtyy1jjbnqpuP9iaHFADuUG/GTlWgEVapCzk9B+Rb9bgOzkT7hVrCrYElx/U+t4HsigWuskhMmJLNdwBNDNzX3UsGnXavVgXQCNwUTGlZXValrFblCknBvgr2rWrAckoAg2AVqU7uA8+23u/kkmRqXR+3Jr+MGOoxOi10itex5GzbX+c/YoZTlEFtFii6JVvh3GvDrEQM/Ikewhu8VPS+RVX7NzPlLG3YKjuGKsfsXYtYLc7EHAwR+kogETZQplfqI7OPgypfi5Qqp6reKkvOroxl13Calowr9oyIhII0hsaqiSsNDg6b7ObmruhwB3QAqsnbj3eUWcukFbGvayUcTr74fyWhObNygsqvk+VJcEvg6z2FAacMeQRMGQ6t9SgnnNmqFo1NWbkBLHztEbW/A/EUDjZytTAU81OcWcPDPHyoIJbokRYfxUyWfy/r6ANwDu9C9jINoSmRwZFDUJi9/M2d/Gk0DJsQ1nQ96OBmQy58Fd3VTlZRpdnL4N7h6S1KVhXiHj13kasAfIOiaMCVmsXC8kh8awyF7hZok26cHvwof2cmBi1sNQxBDmI=",
      "E2E_FLAG": "AgCAE9nXKRzdLg5RN6dxZQnNSKBnIv/9MVov6IAY8hmsrtcuiVg+q07zDYpXP808/USPGUzs13LGY9/Wa5Itys5dl2hbjBM06VbMwW+kId+AulfPsMeJ8If/ZJibsZrpuOZLUtGsqUS0bBjijKw3g9BX3zwFsSCmptJPaPKehG4HZX2BdGLJ6dQ3jZwLj6jgZXnCg1Q/r+dj/dDiUJ3bE3CM/pyRUttEhFKxKZ17Sk9FiWarJTFDtMaHh6ON9WK3sky3pIcq/5kmtvfPTP41wbJ48dECkvMdAzHI4IDhBp7iUiGUzDtNry0T2X+2vzFx8UX5SyMsBY99i82P9FykjmDAB6OWom/GAMYg+rsPErnUNkdI+eTZ0HDpclhORzYv3T0mWNbpcm0ibQEBoBfONKevB0DwLYLuOVLskqy+jIQPZeBXchZAiM0YvV8Nkz6646nKj3OyQD6eQDdMDFoqPsAkmtQzzpmGuRE8LLAdIR7Xw5nzX4RzmqbkBG9uaPAt6ChmS6b0OOkC2gQyZuoRcK/7t1+jzR7TXpp9tn0D4XA+85uGbtMc26SrmqTVaFU/2x/bUeCeN0ODnszdk8jK77n1+kYf3n9F8EVZTpPsf4EVRJj7cyRbT5RUWc9ridRWmmzq38vXgO/xhxR+udeRFT2a6x5TMWRmt0hD6GlokxZ40EW/CB4CPEYYbm/YtHp9IonX84I="
    },
    "name": "vars-r109"
  }
}
