{
  "containerPort": 8080,
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:7af7fcc5a975b049b5c353c87060dc069a51210f7e705a9b07c73e10f118086b",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/27"
  },
  "iris": {
    "deploymentId": 99,
    "serviceName": "test-project",
    "targetName": "aws"
  },
  "release": {
    "id": 43,
    "sourceSha": "7f061109e2d2b010c38c2c7e2f016df4842bf0d8"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "test-project-27.likelion.uk"
  }
}
