{
  "containerPort": 8080,
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:e07878bbeefff20b6dc93ee3fe3d60a7cbbafe4c89842c5ae95cd1b9cd9b08bc",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/15"
  },
  "iris": {
    "deploymentId": 29,
    "serviceName": "fix-e2e-cb0b72-code",
    "targetName": "aws"
  },
  "release": {
    "id": 21,
    "sourceSha": "173635d849c598b5125c26798d65acd3d266491c"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "fix-e2e-cb0b72-code-15.likelion.uk"
  }
}
