{
  "containerPort": 8080,
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:018c7542fd2a96aab89455ceb3beaef240b17dd17a40465081961ea9b75ba708",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/2"
  },
  "release": {
    "id": 2,
    "sourceSha": "f54230346fbfca4e34ae2cdd1a370217611d2191"
  },
  "route": {
    "host": "portpolio-production-2.likelion.uk"
  }
}
