{
  "database": {
    "engine": "postgres",
    "image": "docker.io/library/postgres:16-alpine@sha256:721873c34ceb9f8d8fc265984940dc982404c105f19ad51be9fdc5970a6080ea",
    "port": 5432,
    "storage": "5Gi"
  },
  "iris": {
    "deploymentId": 271,
    "serviceName": "db",
    "targetName": "aws"
  },
  "projectId": "56",
  "release": {
    "id": 130
  },
  "replicas": 1,
  "variables": {
    "encryptedData": {
      "POSTGRES_DB": "AgBNAGelYSm3T4qptimtziP/v+htCqwpis6b27w6CFwojqJhbHm9AqMBq10ndIg2CbEKp2To21Em6rSr4WnRTZpuQc5jZB8x3OpmYiownthY7XrL/4cwTN/TfKlx5jkpj+pD1KYqBk4awKjTwIcipK48xqn03ToPAkV6dyB0nNdv6LW8rmduo7uzLNHNA0yDdCOYG+swE46SrBtevOWxCZ6CIxGdyrcS11pA2rh3ReulodqVpTM4f3a4n3EIksr6g8f2PPn5ehIOytlfGkFroAPjfLA0X1dxEA9VqbUjReGGIZ4ktuRzgQPnVnPC1VLe3iToSwLggtZdEeoISLGQvnq800JVfWeGD39k7P4X2ztUmm3Hu2sPhDVS9JYQcVDGgWtqzg6Y4WS+3d72lM8hQQXaXmUzQ6pxvnbeHNvsQjO+hqIgiHsrsOA2mjjKO6o52v+IzmdPDYSmycYWN4/HY2ait1m+rq0F1caxQYNCTNiIt9uEd6KRkgm05kEPHZZwjHo/rNbhX4CU/+auz4DDJcm3cebEpsyBwWnel2WCTg8GAXU5P+rFCvfKLF29Am1Mw0ZR4WU2XiM03Tb9ulMLrXCdrZDvdZscK1QEEh0Wxrk5NqnAfFjzisSulLN3syVfFdbFtS07D32Cn7VNaxVtKCbuX9Uf5AqnPSnAaskqrpVET9utW3dryQr9u6S3vPj/RqQHFSFE",
      "POSTGRES_PASSWORD": "AgA73Oz4KRhQaT1gIWk0X8ab5KqiOyzDH2HGo9rsWOCp0r+/a4wTWYQVDrWxyCA5qEkWEylupaaJQW4zoaL0PuWxrMwOCjcj9eeaShSdOrHGT9zqJGG2JKVCgNJviAo7KJZe5Rp3d8gBXIod4zgsAc4BFhsxc2IPVbuUVng9FDG7huu+i1OnhlHTKXUmhWBmvR56JmKpSWZcHKPWm8jYHDOg3BjCKu+fCnLh1nVyqcQmhHQ5pr4erlfOE7KnDIblSrn4PNPVA1tiGbtQOvbA0O+kOvGEcullvkW59P2s2NJH3TtwouoZGXmCS9SHE1/5xb+K5DUjyOCKHM0anbJq1+UdE8ZWfaNuU45u4p3Cl7tI19CGWwmEyInBC+fgo7R0BpHmBTJyhwpFnqQ5UeAPIz1IxOKNMkV1Crgv1q+Vn97f14KwLkiyDguCPljvaciBEFaEjMWNReu38jWE8Ta4jXG2L8UavV00ZLBSnnxqhHNIbTGdu6t3vRzAyRXPi7scW8F1WpcPEjXTjTiIOgflq53rqi/ORWL5Q6GfWq3bOo+VELYoJMi50eUjoXG8dFAgzcaoO4H/+I4cJTrhzfqhpup9Z52tt2Y3spopMxGNjBM5qZB42W5J27Zb1S7SBhwSMuUG1yuKB4or45cSk+qd8yz4DA0WKRTuiLTmTgq8PmMq0Jofgbbd7sf11jLkt4a9grrush+uTW6gzIzgNyOfm/ysTGdq7WgRwadya895UYsSGA==",
      "POSTGRES_USER": "AgAirZD9gCJgn6yh8V6AX0Q4ozbKJ4FfOZaJ3+vEG3LlP5yEiSO2uWogBAtZfBiK7GPc0h/Eqn5loYkFVNIZ2FKW1EGFipYTNSSMQukei7MtaYTvQDRQSZH88/BYxy5fM7da+4DpghKg5HfxCpaKYV0mUmeRZU1aUK6dYhmtZW+GrSB6G7LzG6mkdESqmDbqm/o2eghNHy5+H8lhZxay10lgZPC+M/n7mUlxuIZldrENCiNX56jFOO0hspxSiG7oF0sX0a5hjw4dZQoOxLoPCI9I1/oOe3WQDoU5j7iw9Rjft3K7PGndxtOH/RF997+dWpJVVbvy/hyXbnPUBkNxluAptyimou4YPyjYLZj/I5sceqnVzI3FVVwTPIaQbIGicEduDSRD8A5HoiyWKuxaIw8XULPDogpIpJQ9Saj10hgOFQF6V58/2dZXQImyNlqH2rCScOqAgMTSHTEd8597LKl/L9Q+o2vrtIZCzBhUoapVTw418jDMO9VoiSXJQaE6MuM3q93+lExSelyEiJ9c/KkitxHv3gtwRTWXrARhCnM9pSH2cagbPP046s6oo843RZ4yj0+8g9jCKNyafd5mdhfEbtvHInV6ABSLhnO4S1nKug+bXdFPTceeibjsg2KQ9c/5K8kShAAphDPBW8LrOY+WZ87fquxzRj6QvHk7jcIcmEkIKmRvzZbhEqvLSo8i9OZxQncV"
    },
    "name": "vars-r130"
  },
  "workload": {
    "kind": "database"
  }
}
