{
  "containerPort": 8080,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:c61d9ee1e4a37dac60e527d6708178323c026a2bd599eb518bb269f7881f9cb6",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/24"
  },
  "iris": {
    "deploymentId": 147,
    "serviceName": "temp-log",
    "targetName": "aws"
  },
  "projectId": "9",
  "release": {
    "id": 78,
    "sourceSha": "03c736bab48fa2f9e24ed7950f0e27c11138e877"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "temp-log-24.likelion.uk"
  },
  "service": {
    "exposeContainerPort": true
  },
  "variables": {
    "encryptedData": {
      "MONGO_URI": "AgC8DARKFdLn3+9/jgdY30KA0hqOm4oC6dH1MwBzxkKhItDsZDDO76YwYitGyTb5OnDrmzZREeEr/n5kkMgje/oI+kQqs7yataOMtKFUW10CUTxtQXX9ymahCL1ZmnGSX2blTBkLw16RFrSCsYAwVzYpKIBOsa1HSNlPXw4NwNrEVRuYzL/wa7oX/1gDERpl6tfpdzz6plnUfJTMCNWcKyxuoHwa+cU7faJL8/6PlBXbw7LV38W2tn2gGcoTqB3IbS018AEE5Q14PyG24nx57DbzQCMrWDb++abZGcO8oDrk0s4CVhb2zkbNfwAgggqdloML9WfXAI+4MGdqZyvjeCXfGNUWGsxV8Xqd9JZZD+SBPZY5K226pWWkLZfag9HCjHuzU6h6KU+WhB6sW2McyZDhYJAJY/iAsBmK1NLD95oEuWS/XsNH4R3PfL6P4NrUrzL7FWyDmEG9J8e+IexobP/ifMfXFgQoYeui8u79+XnTH+zyGmTOkL9ZCxD800erI10FZnswIna+AX8hlFaAzGGZvq7fpIZWcqnqjDw99fHzhQTz0UuejIa+QiFFdsw/BUUqbx7zOU4y/5IqSGYsZzvaT7YlMeTG2vwvgdNdxKE1IjQkz4JZXdRhj4wuZRUdCQStZvp3pdCC89JrQj8M7cGYFohXVbsr2o9vcGeAf2oGD89qqazRv0cIUp+n9ZCTqRla35cQJhFAMS/UTQUK5eMiDH/nqBmNQzGxMqkqCWrf84KNUBDyLu8PefXbg/1894Uu2fyeGKJw6hwS/SO5gk6cvisNbGRngVt9GsBoRQ/LHp+pxcU7WgLi4A4ODKH6XlKrGk57/UI=",
      "PUBLIC_URL": "AgAtxVvvvVH9+DazXHkiTJBJMnU9Wr4y2yuIm9iZRcsp8TXwPLzlg+wXyVAox2Ck36fA/wJP9RmbAmiPz2H09VyX1/eiy5JO2oLiU/g/aT/zassArzrWTucGvC+PBMuD0H8spKwFCBCAEF23hYchZ1Zxf1RLOq4nEcBtdooKVhWtvYhqBp+x/oBfGUm57a68uo81qUJ654V+2hioAgNngDA2nSHverf28rkKTjRtLmGv+El86EupeIta0UIgWLMzK1GMsQVDCl47VOPdBzWru+hHnJDqMyFBhIFbskJobrXrjPFEHBI9OKbNCopdJ7T88+h+AtocTLbRIK/hiZTi1Z3wc0WEbNMIMsEHCVxblmSqevHgglsaruqrhz+fEVMWoL5d2njaNc1FKaf9m9eQCleHD5hLcUmuQ4DENg1n1F4oT3OAxzfpc5X8OVXJuiK+RlPyZtyN6n8MeCCaC4P4BsZ+qvBjH9fXNE7rC5DVxE5uHhcLvj7wyIeCj0m3poTiX5qXQnvdjJNJnOXa1kOw/oGIAgWFjvNOBKC27u4aKOfLsi7m1noAv1HyMUKL7EpYcamhgqY9ulZdDZr1C9X7fi/UHw8wFijy+u/403BAyTiSw8DL0YFCwROGkCb1eXHlaitcPhUj1MVlIJj/cpzWoJl7xUrEefkOlbGA37R722QuqBEAJyAsWwBiYKVMaGhS+EEsYOrOscTNL2PPZNolgdfv+94rL03VwGAboZjDD7Kt",
      "SESSION_SECRET": "AgAShWnFncHUfmbYf9GXDeISppmUvN6Y4rihujjpXwSI4rQD0y5Ax5Lkf7Z0B9ORk7eSMVdpi5ESSuMlRUfAAhYZhGOstx3r+XCtRORK7lx02XPKUIeDRzwq01W1u2BWJZSXuuoSyQcCgkyoDkODeX4czDsyveEx9zhiv696sqNJBQeij6N2+Ed+OADd+ExZQibTCDsjUAB21ceCEUD2dq8/tKSYVo+wJMTnrproiR8wWVWqkjGtY07sIzzy0gXnRKr761MOdCAy7EjnYhKB7mwY8uPCZ3639vY0Q11Ysurs6J1sNjgYBro7wo4T5GEXPCC4RHd0nGr38kafLqvfk6aVgzfI3rHkld7Fh5p7oaOCFVR4ObNwVf2EMYn+yp+ikQc+aVT+7zs9Q2WaW6Ofd/OW3tbdZgO/sc7RoLmilEmM/KER6DWd5nkPNxkD37AMynsgHUH0ntV/ePalwHJFTexk0V5jM4Arr2uJN8gSYFHsac8i39/9QqRLu0jfJH9R0IsijqfwDNDBJBFsgQFZECj6Uo15aQ2dFgDBLBY2UrsrCal9vFLmwAYMyPdW5L6fWuhQA7v144h8LLnddSvF+VxrbwcgreavyDgBxgE9Xi/Jghdhsj/9cUDtk7komN27HhP+QiQuzNPdjJyXfnHkri7OfQxXDp/lO8pIoruhVlb0j6G7O5lnVtgD91RT+WTBSySLwRRyS70WmapGsW9D6Yf0iJ9aCMOwrGFpg8CiQ4LIzNbr+uXnZCc2dDlNHjKUBlimdvXP4yeZVbk1L0whhQ7x"
    },
    "name": "vars-r78"
  }
}
