{
  "containerPort": 8080,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:0437ff327385494a244ea1213daaad2eb3ebfd6ff4453b63e09ce0503130d5f4",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/24"
  },
  "iris": {
    "deploymentId": 172,
    "serviceName": "temp-log",
    "targetName": "aws"
  },
  "projectId": "9",
  "release": {
    "id": 89,
    "sourceSha": "42568f377943e77ee01fdda30ed833d96f9defe9"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "temp-log-24.likelion.uk"
  },
  "service": {
    "exposeContainerPort": true
  },
  "variables": {
    "encryptedData": {
      "MONGO_URI": "AgBbSUg0MNQgtZHFcXw2aS045ZnfPmpAb+dl44zEtSCNZmnr5RC++I33vVN1HRZrk1zBYmhf4bkzIvTPPzaUSAWIv5qWsfR4RA0LcEeT6QWBdpp0wJAMYzGthfBSzjnN09afhRugT+WJvyMMj99XV//G2I/ZBSIgX+pv2rFjXPLv4/IQ5ms8dlghNiMxvWxUP2AvjFeaQXJvPug66IWsivnPHPPtsCG1pJHbMG2hvhdWHLY/paKkIRRRFN4ksK2iwTHmegrSdw1jmeG3DicjxlVrmsTFvT+7YLHm0+XmueYIXeEigjSlo1XTXd6G9esCaOSHJjG0RO2M3n2ysQfu3CbeQr1Wo13F+yFWq7z17i4n154ZRwBO3jmoLdm4vUUrS8QQ8Qzs0W9+GR6sXTxztsjM0N1XK1Ljk5P/V/ylgp1qnfjdcnih/GQUgb1X/4Ze/ZO41Yc6iAr9xHkRpF0E5j0jV3osADQVCzOHX86ICL6HwUWe1WwvshSKAQBhVi8VeaekFgHeIHDDiRTCP007jnOPLBZMSLCZcuy77PfqYAktiJZMMSDTSk6Mr4hMEVUDGVOzA4ucMPWc38fc+UQxBLDgwBhCdBLmTq0PlzXvNb/VGrw5WkODeGr+hIEQkIGI8IJ12HZFVSbL7zzScfeAFw2FB4SY8Y967Ewjw33hOfNzb5qsKK0CPhoTheQBVkPlYCAYqydanpxhDrK60jvnKcuxGCXZnrgLYbmm8yXYNlvz7L16KmPidfHkU+brBnRB8F/fU0u3W91BgT7TuLPHpLnYwDdmMzcX8putdx1sDKOlAKEASMzWevSTy3iW15PAEGdr4lCncyQ=",
      "PUBLIC_URL": "AgBm6elBd8AdaTyCNnQtcE3fPY2DI9QLyvPIhNaBbjovau6XCpRkFNBxOkj2Ia+Q7cXVIUqLlAaVX/lzazJJA8GNxY1+o/+hHt99kWBS9kXIngraZeqv0wFJppP727DsVvI/vofDwQDQ4tEUhgU/Z37HalN3LXFNtecc3Xwk6zf1MwgVWCTwluAp3uOS9fPXAv1kQi2gq5lN1vV2tTYzDe0tQY05bnia6xZJ0xe6dARCEr8o4+pS178wJ2HslzAhDeEU8TjbUyRJVkCUug/mjCCNwZLz8YgECxpkijoHETCI2VuubzvLAhvyWJ6qjOSB5y+1jZ67onTMQzrxJVG28he0aK/snYcrSirCdPfQ0GnX/HqLWWPnXy15yi2f0Yi1D5lDkwYu86O2AdTu1ieB1v+8ijTRrLFwfmGOzZyeP0lOPvSinzt4xtE1Ao1yDpVSGrMZ8ABI7WgL5yXg+WYKP11EwcgNhOT0XA5QsNNHEJNXxF65Ns/oFbv4Wyfo4lQ8GbmHeWCKe7yES9KiOkqVvAsVybhSIOOutKrDc/0pm5pRTglAk14W2S9C3H4d640hl/cQbe0MMO7C6gDS0j2rAZS+DQ/sevUvNxjwMzugkYk2JqkvsqFY+KPtjkrnl3pr6h2o/NkdiZ0y8hxpEyWx5PRORytewrnjeeGERNR1RSuNTOPRJNZ4doguTsjE6egSpE5v9IQaBq08b2dgc57p/lyXbg/A0kaVb4PvQlO5L23v",
      "SESSION_SECRET": "AgBDDHQjqji9fczUOS+e7YgPwM/qb7RH9BgwviELpvWTtJtkLwatP0phI939eS3TO+uRQQxRKD2pLdkIxd83nVdsr5hfUqs53k0p+TB2FaL/j/Ki9mgGl5+kIsWN2MVpaT9ydMwBTsadiZuUDB4L5sme6wjUvY+i0iFzTj+fK200d7NxxYQOi05Iz0LmjxdcM9bQtyP7sALtH5b+FcuhKT117EYSJ+mG/5CX3ntBOi0nP1lDAJoxgUINl8ifkOZkpKh5qWkXZywfuNciAqMV1kf9NNj5ZHNlKO6hA3UL52Ay5A4jzoMeqgZQtDZtp68WFKd9fR8HFk1dyQpAMEV5nC4yxQ5Qxhkphgvr49Ma8IbmKgaA37zAlh/71EwwFQkaJbpThYlB89dwBNvoG5GqucTqoFugVHb8WE5kT7J8TZhvxJF5G9VKGsWJWruESoljr7TST7IPgTH8TqZdf9cv08FvTVvKzdwxKfHUwA92ajpT9xQilVJM3P/R44bwZkgph3kJtDmNllZAtIQHxn0xwugrMGSZwhmHffImvtpqUj+mPc3ACFmAVKuXpzwtV/WHFD8ki2s3jELsrI48T+W2fSkTMmkzujBNeCHPvD9QY1xOTDp5JpW4EoF7Ya7/kgOvc3Qm5oWwL1Il8ky6YH9ltOKFIpkY4DiPMg6XlGP56JNNNcbBJHAMa+OLdvUepqSAMIrSqnglcTeqkiSjiGI2O3SXdwHuXuZ5ESHNCns99p2bQCGwcTldqQrdMprPKXzhMx8+zkdLUqxmStOJJ9xVGufu"
    },
    "name": "vars-r89"
  }
}
