{
  "containerPort": 8080,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:18aa31e89be8dcf9a8ce5408af63bc9618d357eb71b31ed04bb3618cf77bf8c1",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/73"
  },
  "iris": {
    "deploymentId": 238,
    "serviceName": "softbank-demo-1",
    "targetName": "aws"
  },
  "projectId": "49",
  "release": {
    "id": 117,
    "sourceSha": "b3ec1f7cb93693dc3e0f4736bb069ea4519b4d0e"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "softbank-demo-1-73.likelion.uk"
  },
  "service": {
    "exposeContainerPort": true
  },
  "variables": {
    "encryptedData": {
      "DATABASE_URL": "AgAbVW7hxM38wf1aybjnBQsRxJo6CnfmE4Mj2AbS+wd/xPv1OHS1CdoxZFsqR8pZyYxqejHWpf5hGRe+Np+F3ex1qVIFG6dW2oXuwv7DJjxgYhJrASQO7nPnbiA/RzAcYsxVoxhznZgpB/LRkrRy4ylGT2TZMALXEZHBao56rmLzOlNl9M4Z3HBP4tfJGOQMfNfXqT0W9pBrB+wqOJlnbugvxTW2JMcNm8IpR/mVFGVsrn5m4GA/y/9srQmqTXgJVE1eZQwPkmQcnsvodqACfoLF5WC2+8Qcd4uaTUdY/+3RcVARVsZ13thiLCCaAoJykHdSVh/vkqOXqrNt69DXSM0pHD33kAAbumJ4QzdBZ8tms13K8qt/vIVn7HDOi9KMhXRrgMVXHkrIVitD8Vf536Wl9gtH+wx+eaOA8Qw+ZtQIEWqEggl6scIrhq2+nVNObpPqwSuKilzTB0V1huQmULxJZp4TJ0L6zHzOgc/Ue9wbtKntL3Tm3b5TplSykn5UND9ONuGF9ZdKTnnh+ljpeuuxEdoqK/a4WqKCgxHSC5ieVHwgYNqyOKBhUhRw1bcWeeQKjKIzNl+0L7orMs1baXnChcq2i5nN2Y2DMs3oSsccn4LOl/pAyawmIncxy6z/6L8aYkrIKgmDwm+aM4yjU8qicivN1UHELYLHZ3K83jJBokZPssmt2KkB3TdDCFDxsPiKHZ2XTVyhCQDPnsQOl/x3oZVJwM8Yku6xDHGrrfxymspbbrJpZhH05DZ5y6IMAEQlb1Ftv4ynrJrOEjNeyNBaz4LRMOxlWUPJJaWCVvG3Rnw6DSaunis="
    },
    "name": "vars-r117"
  }
}
