{
  "containerPort": 8080,
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:39adc69a3eab5981390a4d747c86bf91d5a8a61192ecb36f99d6953d82a4937e",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/68"
  },
  "imagePullSecrets": [
    {
      "name": "iris-ecr-pull"
    }
  ],
  "iris": {
    "deploymentId": 244,
    "serviceName": "e2e-disc-svc",
    "targetName": "onprem-u4ikhfig"
  },
  "release": {
    "id": 121
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "e2e-disc-svc-68-u4ikhfig.internal.likelion.uk"
  }
}
