{
  "database": {
    "engine": "postgres",
    "image": "docker.io/library/postgres:16-alpine@sha256:721873c34ceb9f8d8fc265984940dc982404c105f19ad51be9fdc5970a6080ea",
    "port": 5432,
    "storage": "5Gi"
  },
  "iris": {
    "deploymentId": 267,
    "serviceName": "db",
    "targetName": "aws"
  },
  "projectId": "53",
  "release": {
    "id": 128
  },
  "replicas": 1,
  "variables": {
    "encryptedData": {
      "POSTGRES_DB": "AgAKE06Tp01xDNSe7eVRpNHVycGkGWRHCN+0sINM2tOz2wii6AYwkIuXFpBfSmQI23Ml4RHiJxhQ1+vQPv+pfXAamSZm6n5o1/BZzMMLQ6AnIkmJZBfqBDNOKJR0PydvwRH5+N81bhA4GHF+p4rmcBD5WuIpsTnIA53BHwYtlMt2zs+dQfzplNawVdnRslSXylTX/plOpJdTt98I8bvrni4XqlNpQw31JmS01bi/0XkcccokWUMwGt4Mp/uNr4yL80T5tfY/RZbcNtZo+GP5XS9E0OQInsGfElOZhNkm+NlhPsj1pjCVKSWsIeAWB2GKonioCneNFmF9B9MTdzFKcmdXHcqlJUTWIwxuqxW4MA+x7spBFEOxpoITMlgTFlyFPrcCJ9sVDZPIBk2LYG710+4lRRBSW6OQtFzV6ZAVVWOYRGn6SXNXDhqmjfhPMyBDxcM8VigxrwWSzsXyETMN8uaKH4P6wtfoMwrbmMNysDjNJYZNQ8oZMxIDXAZfgrAmqtbjO1+7pN0WBHcyJdDrAfghdqVUSAeeQcK/LoQn5avFFYgF/NwejkPYasFtKoIFTIF7cAr9CuhCjEoMwDSp+0ga7QfBjJmQq6q6JNAiGetNSsTwPEWsUch80/P0Lt5va1Tnq5oNeMm7HjStk1tsjaeitH42R7ftsLpZBGunPckPaDh/1x6ms30L3YTAhblU5ZHWBOnv",
      "POSTGRES_PASSWORD": "AgC5YPy8agTUSRsc4IFFZL88jfYnOvf7E2/uxcSsBn9Fu7A5deUipH3hz/Y0tGN4Ix0jCgnaVw5VPVL1zwZnkhG+H87A0ox933IREIY/73KeYG2DQZvgRdzE9xisBYRbKBNXqhQjS9do/a96kGj3oMcN6Epxp13Mi+qAGvyedvMr9Gduhbn30YQB36pAuuf8Atyvl9QsMHYzSpICFV5RcSDwEJD0HaZt4Vi7FuPFaIe/748CFejKX0klsZvdnTlUbse6GvLb3EWR5O4hZ64cNKRWcqYtcHxxo+J5jp0jdYT6xq5VWYCG0mPBsvnTVT3YCdMNJuCWMjq3Nq+OSMTuzsG5ZWkFgi2ScvgJGGoQhRpAGrcWZLUNvfZo+IYDmunJd+lDRGxqJItC32pOP1my4wUKYKEwxxbGL6Foo/WmVCdYQjJV5dJLBpIH0eOR4WNAvhS/1kMdtTHYiXF+WZnI5QI9Jl+V2cNNeQXl36dqziv1hM3MgTdL2a6jDvw7DXqvx+4xb+NpcCAthM7iK/u65mXImF+MigjGwidbBmp8E2YdhwxESR/ptMnaIwn3kalIV2jaHdivY5G4rYJc0eBAnKuUJkoQthCPxCVYqY6oycHEF+KKM1AXTT8DCq5U6YHLDewkBjMgtAiG8jsCk4sz7f/ccH4WVYoR1UnT4MJ34Jfr+w5Na7973HLvKedVj9O9sUTm4D30DrhASp8kWCxy3zo3wenmUb1lkHf32cNTDrSvMQ==",
      "POSTGRES_USER": "AgCjItJrBivNS1ZovaFQRZ+iVQCKkF31QQZ8mfgrJCNoxDDMItGSwhBsi2/UJaudT7z3vJpUK9mX1DHHAxhcRqsLEt+/Re+xmKAee//4c7VVtJL9dT1dlknf+oYNwiDOEsZhPQHL1px0tf+VVH4Oq3LlCWriXic9JYMAsCxL2lT+bkx6vOhKfNpxW5nOfJv5Yf7luUXWHWWUG6scbEpbqjLUQq8wKeJTcc4pR/VNPbl8pRVrOY53QTfzGbViLbMHHnPXDsCybCXO6vkHg3rdOIMB2JohFO7dY3mhn2e4vWw+KsKb2SmPHztZ7wZn/A9nUvejotgNZ93j1jdprDhR5exPu8shZhASsZ+GYZv16UpgF0zP/7TYTad+6kv6jrm1Spivz2ku5ARqAMsFi05Ake5QxajgPWxV9zliC2Y9kbOFBzf9LcS/PYLN6u0Xa2PgmR1/S97fcB6JrnfVLeHtwLwbJi/O4Je08gm3RZ6doojzkAh2BQeDPVfAuvjEZSSP3q8s14nchMXVVh3XVyTS2gwhllG1zu0FEO6b6oHEshtapQWNx+1YGk8ctXK3UBZcGKvfM7rVhl9MYutNL2gzLEZUHyckgel5/y/w1/qDHWBj6bo5DZZl+sC04jtyBVNfHCDHbPCdy3zpmNUWZ/+hhS2qhDszrSoyqaNPSMMU4FMBW9Y5yg1Tj6+LpLMf1LvnJTB7Q5aO"
    },
    "name": "vars-r128"
  },
  "workload": {
    "kind": "database"
  }
}
