{
  "containerPort": 8080,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:2c8a29a07b6493fe7b5c09a5ebbd81f8d00c03891388c713ce66fc98eb74d136",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/36"
  },
  "iris": {
    "deploymentId": 125,
    "serviceName": "temp-log",
    "targetName": "aws"
  },
  "release": {
    "id": 63,
    "sourceSha": "54fa8072d9fbf817e3352f8eeee2344f37c8a813"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "temp-log-36.likelion.uk"
  }
}
