{
  "containerPort": 4000,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "hostAliases": [
    {
      "name": "mongo",
      "target": "app.svc-41.svc.cluster.local"
    }
  ],
  "image": {
    "digest": "sha256:e76ff908839ee207a29a7db11832f02146f93596f457ec5b6a3e87547608d90f",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/42"
  },
  "iris": {
    "deploymentId": 149,
    "serviceName": "app",
    "targetName": "aws"
  },
  "projectId": "18",
  "release": {
    "id": 81,
    "sourceSha": "03c736bab48fa2f9e24ed7950f0e27c11138e877"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "app-42.likelion.uk"
  },
  "service": {
    "exposeContainerPort": true
  },
  "variables": {
    "encryptedData": {
      "MONGO_APP_PASSWORD": "AgBc7hSvidmPCu2GptquVku1HWRZ2a57ZRWXHTU1hZmeEv/AJE/LoMCoBHkW/de+ACyJE17iuxbZBn1J5ZigmfutGRPYQuKtoO/pOsU+Fcr0WhwlyLPYf4N5JwPPBCDsIs1b0+d/FkTY1jfmTR7UDsBJoQJvDaQdzlTGdL+qonky/5kSVzw9R79GteVrzhN/rQ+nit6cif95IfVW2LwBCwHYAqci5qUOZEA/r6MRVCv8GzKEChN0OI0JtdyjJAJ6OOecpRZLblRw0Rgfcg9HNzmZGuN+X7fZX4XidlA8ct+5Ut9S+ELi5ZmSSpYzYcP7Mb+d2YVDN7yMW0oTzg3uyibcOwjMGHf8msJjiFUOpbPw/Vi0u+fBPWfckZTkhZB7ZBU4ooxJWatXAb9ALxSDp4LzSAzcwXhuykS0cZ7t9lggFMsTs3SGHmIiTWj8f1esEwNUEjs4M4hgA3lmnMoXyAuDwzSzSejgPH4H9Dc6aCejMs6v3z2Fwj/osATqLF/TLe4v5QNWsAEY2IJGgUlU5IXeozBs/RZKVXp+tgbqk2Xe54oREtmbRvO2hRNG/D4o2CIK2TunJQLldvwRX6kUMQUlgpeaPMnxDaJRhV/RhLbYHqHsUSCNNvSD8rITSsDOpAKN60G0aYQylhFhSGBWEjDD6r6NSmThiryYZmmtSuu5koPM89CFciYyPVyQlpoPEZBICJSkxkATzynz0dH4McZyJCl5YC7mdCiCF2tULKNoS7eK8npP3hdAqqPAYDkYFR4=",
      "MONGO_ROOT_PASSWORD": "AgAGuGn5g+WlXkJioJZIdnaq8AssIFPcpZTD1k5RWHI0JaU/f1qWbWym2UHqdbRbPSid8J/JOqXA5MS2AvhzGIweBor/zRcyOFNLI4fTQksbBNsZVJMp4aXFfg2oQPufcjA/dzUjs0URrEtcmMbVnPbwwTg5NVmSYe8JmPK2pPP52B05DjkZQ7u5klajMg/Md+swCliDmGFFFqlb+8311cCaAnV9Kvmx1b2pq+XZKFmP3fRe/eQ1tmgQFlq1LQJmd7T1V2AiYkNXPUc6qgEF4sbVw5JHPxW+o4LB4Cc+AlCzvd85wOEMaWZUR263m+IFfTTdOdVENyz8+nYVXne5YKN/lAQ/WWHUrh0zo9+LFeWxB+nXP7Dw+jIgUK9XwGu38AQ+Axakj4D8kp4KqBBO5EmxKLDDGZwrx3WMEZIG1/19Vet+nczh+bIOF5f+DAOsRgBSWLokeisRd5DW+6aFlAbpsme29AyClkW9nqkv2GGQI6YbTRcjOQcQT9+6Z2eNfzLSGNkgLkszgVpVzNqec8MJxtY5hvGzoPybbhQNBkmHU74kw9zqypDJ6hjiB7TqTA2tqKpNOBjvJFmHDTVzdlT3+tUdNTaCToUqE+/x6aDgkOTMTuoBEtamG9y+NzcgWLVS0Sbq0vnNbuzSjEIHCzoUD+zZaWtmGgW68cQyjhsGlP0rvI1Xd06T9NVsGqrQlLZ/EhOe++SIKSZbgdLAN1UdA9XxhIJFe0PXYZgxXCx6XQ==",
      "MONGO_URI": "AgA2AvFEV1b4+LsPFkSarRA14RqeuJy02HhixuNMfXxZqO8+V76S49P/n/aF+iBYQF+eQZGFI32VNgCTGt3BoawN9DXTkpBTc7nOaQ1PTr8o7uX1BX2NTekziLDC/zxSFAhKxi9JKWAsFdkYctCSU9LP5Qkdl8VT+6kwMBUxMCFrRAtkVXn2A3Tijh7cV91cFlwO8rW4Bsypbw3YQkm0WDwvw3bXZI2i7IHU83U50fsG6V539ZKz9RVES94St93n7PAHSsAbz3taZOJyla8SdtfS6XUNUNWXRzxSL8AzhRQq5E9Zg3690zJ2beqgVBUrCrywSx2Nu3eQg7LxVKCBubYlwL2chuVpgs7EEE8GI01W+qwUphRKHwyAoOvmfNCnQ0ce5n20F0cMiKzqFPPzAuJaRSnUX8UTBzQg2qGuhuYnQ7k4pbKWNaBdRV/AZuJMT/Fs3pZHdyprg3nXHVHhsWquXAUUVPtQgNaV1lBIWp/dgjqTyCgFS0eCoN9uAlbFyMJw11Tjgm5i3PDjZ5sI5CQ/5Vf7jUeH85NhjiE5wY4+C1Vg8pRURhZPcphMIx72SayMF0zDcRLXs0aNj5sOJgxyd5dmI44uYYkijAuIu716YebQBpzE8hj2yutnVP6/YYoJFSLBr2v4VI4FLdc+LSCS0mA5HOsY6B8AHw/W/qZgCCsvrRlM0aYNdXRExPxCzeR7m+3mEienAATP5CD9/6eqTxatmx3id8f22pxhD2vb3Qtz7fGxnlhUM53Fc+lLxuZWRW1XQSe3FIN7AYc1u9VY0ll4v0eiUxY6kg9DgLumwdELSjXP/c7HqBZFuaVD4+r9/IttuApIye0=",
      "SESSION_SECRET": "AgAVn4q9m1m4Raq5Lm/oivNqHMkDYl+nlDtRUKl9qmfRSFPyLRuw9CH05iWqFHzs+D6OrSIjc0A/F7jP8BGHecmKACig9YN5dcxnAHMiqufamhk4xwyHvcz9XJjxpj4aTDXAsU6KDEbDFY0lllYKOkXkNDT7BMkJgfwxJky9DJRNNih+BwdAHFOstXZSs1EIJFZm+eqQwvgl0Vz0Hvk+/wJcWrrWdwM41or+rLWbPV0MLefai/jL1BUlxIe9v4g70vRsTpcYmpgVlUFG6DK/X1lEXL3uryfEMsGshvtR+C/Tbdjk3RIQ6aY9VPoOXSTp35NddlbILCHOUQVZ6JgwYvsZIWnOByGyhghVQg/wWvRXNK+fxo3AL3cbOze/fu9pjYBRUzY/OVKEFo4GqeMdR8Vp1bsyepmnWA6cCgGXPCkhViLTRIeHDoBfjpTNq9DF+tNzEg6YKEVATOZqyBYmGXvsCst69vZGRDEOJRHhzsOalGuCOajPIQG2oqIoh2fKMbS17mW5nKyEl/FXtUUvMU028Id/aY7MkDZywEQLf76Uiwrhzn9/K4q5UU9aJkDJ6H9LE4LRATkcMCv8OWhiD4az7c+0iscroN7iiD+a0Aui0vS0oG9X7UviTgxMGCKTq/LIwK71S2rgWf+aJ22LZg50idRiJgZTCz7wkK7EIq9EZycyJ5NmeeD+TKa71FiLVYDGCis8MhDsobQUetZ/oNAmzTwO7Qta0bHL/ZhBwilTTRl2WE+VvsKtB+GqYPhZaNE="
    },
    "name": "vars-r81"
  }
}
