{
  "containerPort": 4000,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "hostAliases": [
    {
      "name": "mongo",
      "target": "app.svc-41.svc.cluster.local"
    }
  ],
  "image": {
    "digest": "sha256:0846a773f7452fddd26521ad0e9118f230fa19cc1dc9dd8f59df7d5608493c3d",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/42"
  },
  "iris": {
    "deploymentId": 174,
    "serviceName": "app",
    "targetName": "aws"
  },
  "projectId": "18",
  "release": {
    "id": 90,
    "sourceSha": "42568f377943e77ee01fdda30ed833d96f9defe9"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "app-42.likelion.uk"
  },
  "service": {
    "exposeContainerPort": true
  },
  "variables": {
    "encryptedData": {
      "MONGO_APP_PASSWORD": "AgB5gf+U9B2zpdoginQsoR0LB3iriFh5/9Z2e1ZeB3fgj4qAR+/KkWDQBjcOtJAuLPVkExdl4pOiJBbkhqY6HQGXKhowIdOmlYDCSQy272lIEMb1XXj7EgPrf+5ZrKDMQFwZ/bcRBwJFMr32iWyknpY5Dl/euf1B37Gu848dL8SS0Vmu+VaL9GcVUZxlZUlW3DaiC24NgKljfGJVy/t/BGLjOesnbDi6Xf3D/QmTmppOOxCRp+e3NdmBVKi+st4b1DBoDpzxQd98PRSYvZs97d1rsSF9z+dRpvgeUgy40OZfBTMVeuQqnWw3Or2xIBoK8jkm2beK7IUzBWKtSMg3GuNtA54jKmwEGhhPpChGNPKPiWEiLVE/iWK1Mh6ar4mQrjZbnwfCML9OfkJ0dpI5rv/XTjPyGJNk6l2MNNFlTQDyoRP4wQ7hO2qWXdlqSKiedrV9l1xivpQyrCL3bTD4wkj5t1mcNkNNSsySOoR0SAs6LlTVF8YDe7WU7TlKHfointVWs29Xn7SYEh/epuAN10q4KxGRyLZ1sGgGkijCzz2mZF5MIbGZj+g16Rsi8oKn6EbpD3HCbrcFHODAZeLxg78NkDQMeKpWeQzqBVX4XKLI/wyUWe3YfAxwzdYTAU79EPMU1SmT9hkRT7xTPgesNLcWAa1fNuBHC2lxGITyS4FiwflmIz/SyZyxeU/tfy59CyJ1mcMuzp4wejGyzs3v13FVaNnuqosOmBtcXZu0ZAXsMdFfaHjIEh7cpiP3hlaqzo8=",
      "MONGO_ROOT_PASSWORD": "AgA6FQiZA9jRztK6NtP4LjEmQdtjEUc6wHuNF18eG+Vq9bP1DiHop5KgAPX3hKava/JrFwObTQjLj60AAOacefZGamT3oXe0/g9Uqzm6AuwQtKtqune+fotaR1T7u7f9gMeD/Rsh7rBz4hUGivl40vPFElc39YneYJBGNn1sPKJG9PB3Hs70fAwviedwbK9eqdsxjocooyONCw20L/ha4zZBrA8Wzuyli2VHh6EyomsK4oCmhULklfhY7PDJwSq59B7mAJFSBnAYdjadAY9a3FaGVoFX7+pg93C6CbhUAV1U+jgkyHD0b6kzPEmfnQyGPZrHOS4lw26A65pYgoRFQPrHptEfLUVulMY9sv8hxXJqkPK36r5mspQpm9DHUGfSRe97a4dSKPDLdzZX8rqsSYoMRW9Lyk3kVCZKKB6ZA/VIEKgguZvMZcmPCwn30XV1HNr1WmgypDhzjrZxYDmqVrA0QE7lSYJ2W3y1fT5PO76kjEN9yxOgGwqPSmf4ZoLxixyVcY9mJfLokvYL1F4LGOe9nNWPYBgT0UR7hM7/Q3eGx9a87zvF1VinUUJULLMT3lLn61Nzt/cce6vuLO7uNHTxarKsi11VkFoSeMQr4VAV3SXxrCFG2aik+PyAVO31BfdvtzO157AImZM7p8HzP3YMG7Th07pp+pJr1gKbWN4KUI4H58AgiwzWb/T10ewFHkPNjJJfUYezRMJPJyWz3PdhHxagf0xhvFWeMtsWqgL1cg==",
      "MONGO_URI": "AgAmM4e+R5WP+bdjjti42DsPeXk0PTRQZvX8wF4cerd72z55JjBKZj142XK4LPIJ97MNdujhB9o9vVqA8FYJwUSQ/uMYWhBlla52Pvhm3ER2UjqoRCOg8y/77mJGpJNnwjys7OP9axirErVMRIYI7DD85iL7rB/Q8GdUsPAaxi1EP86N1De6AghDn+EQ4U2y/Mm2yr7bl4yZ/04rnFkb9JsTsRGAIrtMln9o9Pyd2bjnTOWSbe9KjUp6rIUbeL3Dxhqr5da4V9dAV2/uyhAab+WAjuBRByndqUzih3ZKKUyZV4fKeP/kxl4qS+e55cmpzDraHxoiQiQ3CfkFFe7ACyIFR7W1NO8y5RaV4j0dcx0/li3VQYzDMH1V3Z9Q4vjj3DQ2OMduXsb3vxgHdg30MXUYWJHXnaMq6uFqYqtsU4r8xz9kWU9yi3Mtd6VS3IqpRuh9th3gC8Q/iRY4RKuvIXMoh4lVSmg1BDU7NPNrCnydO6NB+HEgaeeGFpf0C6goshHPqECDCCcfrwCqdsP9hDFMs31wIRDq39c5CjEN2XFgYVz4YZEyqaoHRykv4igeEDq3tabnhzPY8DcMaYypPAK9mQLiCkaP8rkG9KekkGROf9xa7yJDGTiKIYvaEPuLqUvoj40qwXw4xFbk6r0QNHP5ck2TEvUtRl9TFYy4koUyNtZNqQm2Trz8h+xh8p1GZDpIDjz48InddzDX/HRqpFaP6oTw4mfn1Jj3OQjBVTZmp468MytPtSUCritedm5ZlPL5z645kpxbhgB9ERlbmbqJbmxOuSR6HvHDyuRWBeZcingQErURF9WkHQ7Vj0tgK3YHdOsGe/XsM7A=",
      "SESSION_SECRET": "AgAyk07aFnGejqCTwPeiwHVLJUNGBtkPuPngemBp8+WJu1GOoVIk5FouwOc23IVorFAMNiuqs9qpU0HX12h3qIgBdCCDciaJ3v+3WbX92bOJz/vJD/r03FJtGTNhAJ76pStNtZrEpwiFrMxbmkiVJAPboszaYb6I+U/RE72cNMJgXfOVSQsd5VL7SNicbaM3U3NTn9cy0vb8m0B7T1ZQLhtHUj3s/tFZnKRnQvW5gl29NHMkZ3XS8veh5eKG887/EledTk+mflYFzVSYCiPyYPkh0CuYPQXb4eDHT6CJFkBZRI0xbDZkj3nN+FV+zM7rVHrp5JqEF3Tmxq0I2BLmUajVs/ek/la/m3nPgZ/Y5WdGhAvE90PxypT6NS1kFSSVd3Qsj3AD03jaNGPW6m97fbDswTgIdCt07zYRnquGU/Ytrqp5KD+Lq8zfK+8RN4Rd2WCr46UhbKGKC+mI66nXL9meFbWh1L5GeHRV2vsODQBZx1Ok0NvcvcdLdqiBXoCVLUIrPxOAPf6uIZoeFOeOTS6glFeDViwT1iYM7tx/xwG8Cs0Dky2TG4ypTRUWF/lhVqj+KUvYrzDwkpfunfHTA2pIrI0H6UNgUDqRSZmTwf6CqPdtzw2O+/lVuPCau2EwS4Ty0HFPUqHyqPZwhFlP+r5zoU9YEUqd60RGaBQcn3HRVoiikuowhVen+5aUqRIHlg8GpvtIH7HxusPDP98VX+ia8M798UIPyzKjXtphFqvn8YRbF+DrWcdzw2PyILV26pE="
    },
    "name": "vars-r90"
  }
}
