{
  "containerPort": 4000,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "hostAliases": [
    {
      "name": "mongo",
      "target": "app.svc-41.svc.cluster.local"
    }
  ],
  "image": {
    "digest": "sha256:edc02963911242ce3a7dd6d549935125a3bd7e740aa01dbf088b54165976b4e5",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/42"
  },
  "iris": {
    "deploymentId": 134,
    "serviceName": "app",
    "targetName": "aws"
  },
  "projectId": "18",
  "release": {
    "id": 69,
    "sourceSha": "54fa8072d9fbf817e3352f8eeee2344f37c8a813"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "app-42.likelion.uk"
  },
  "service": {
    "exposeContainerPort": true
  },
  "variables": {
    "encryptedData": {
      "MONGO_APP_PASSWORD": "AgA+Lck4udRPG5cKICamczZwMLwOidxoO8Neg65TNdOd60iKkHWfUMJJOIvQCrM7vHSkdIc1pxA6JjmyAKvf44GnG+SzroREQxJsFwFeSpmEE9wsr1HzM65QWtaIKYH8HhMSVnh9bl7cVn0Y6xP/ci0mVdis/zc8nnAGTc0fFpFMDdwMqoTZ7Y3pPSZBPB/albifw9yFEN/5BSZEetej7Yp9j0G5PaKvBzeiMwCisralB2wWo5BKPFTYwjPMK7cX1HEry3HOg/RBjxhvM6nBqH1HdG0FmgzgMPAP1wAe54oXGEQ0hJ+FkYD3fPoZNniUMZoGTy9UlGl4+zlCEzVIFA+QWbDCWImAq+RC1ebo0IrXW6KatugKvhJ2thruSN6K1Ks2YvPmlnFdKljKelWxjH0n2bCPkiJEyFPEtjUNLMmefQPpskiww5VFylTGWMmi3PeBqBIFdiTBYCi+Pig6MXOtk2NTQ8efvQdzr+hBOC//ITPv9Ms4h/rrU0V74loF//WksYbePYBJX44qB/zFnkrAZhIS7tpHGSsyVocQSXhXNP9CIqHHiLUuWBV/1bCLgNqzb1oFm4D9yyTVNo+PQJeWDYPhbP2YJC4YHJ2q1DGIpFyj9IWgKlLBmiyWQZeKoKOdUp5Jpa8dfB0Rfu41tN8X5gx2Aa/lye162m/KGXyxlPmit+7INMsQzTcxOoipMdpz/GYJcL8GI6teFgdgo/QkEUTPiqC5n6Xkxtzsf9pPdPTwPLyy6GH+kEumCbSuU1M=",
      "MONGO_ROOT_PASSWORD": "AgA9yR3U+VeZt10oRQj+FBmsDwrmIYuy5TxQ2XV+6Y928cWM9uHn+SyU1CBMdudRwRHcCrUsDJa8ytFiu27Ytj3/9nWEUjYg87Xhitemf/0e3BVI4ffOtIylXKwAKa2RZjUoZHSxHtWDNBvtBTUiSljVvQm2ITg+kfQeh0oioHCgLglKN8ogT+ws0QzcVz0MnyRCGWUou5wwFc6BJ+mcne90OJQ6UkHm5kClqrsP3QkjIaMvNCtEwocpewb8aNGkgPHNaM3lzrcfLqCZgByzgrQvFsdr2AyMnWTbJ1nGJnX3cY5NcOIm0bPSoNLRwKHG7e3hV/Jo/K4mRilWNIMESP22mZq5dJNC/MUF28S1PFF2ywqFP8YltP/t8lvXcb2akj1JnS+xVw5sJgUX0NUSlumAZ4q89UnZkYQq9Rk8Qa1rh07JPayPX200yNw8e6tsbTjGWiadlvNRwx4KIdhJrgbcVtb84oRteJhERkd6Lu1laKuj0dZlBM0mxkvWta0/bU7ObqoB+TIJDwfAJh/KpGl+JmPwgRI4XWpKv/VksUuYnub2OJUKWiFP4UHUsbPQPZKrFL6O8Xwya+1J/CnIGky00x9jsVFfkN08V7cCaezJDvChtO/NLozKOfQQv36AF8ME3pxvYEaAv03uAWyN5teGUWx3lckQYG1w/OLE08DE9FMdvkS2pBs+eSwYp73m26QLRQfc9bdoBuQc28a9dF0ZF1zYQG5myv9icLTAeU0XUA==",
      "MONGO_URI": "AgAqS4XDDlIc2/S9f0sn6mbyrOtFTMcPCB/UyL67wHN8TiLgYNRDJaT66tHM+WCTytFRfUESNWpTCtOwWSKCEK5ZoNoHHKBOh4bPsa6H7gWimukxj9pVRr8bTBCrmrwvZz117RmajoCA/UNWo8U+Km7NgTzFVJezmHx1HQmIcQCZx1Fitemb4rAF+cu6/jBULpd0vnt4t8OM7k88EAyql2/QE/C2fGHXVuDQVJ93AOOLIOUBwNaUboSZXR9w8UevQiBoH+my2uWNF5l8ncYXPb3saQkqhDVmYDblXofHtPNm1/26/tfZdfCgved2t99Go0pMMvG4VMja4WLiQMnzgljcHc3OBzePhReDbvpktXXa2wXQqtVU0pwema/lEVaY67sHCMiyWTFQy7HWp7tt+VtrI0o3T+pFuPi5+QWFriq+EegsBSkn2nA2KmViKkmBDoH1PLgPnaMDPRbsmLyRlEeGCwk1kUi5aM2Ez4VQLMdQAnSzwI3uazMbqEdauZboT87aRQojDvNBU8nl2Djvnn38GOqAhxoSFnFlLAbyNLbenKa9PUuTfiZys2HIFhmdpJydSy4o4l+e0KMag3kTAYJ9VNx5CoZ8njCZL/9N8g8pHbd0y5CoLQ8ip3Ko9Wmj5cBqNB8lyE0dZWE1lnoc1+r3famMNfMbLTEiGeyp32bOXNoUkxp57AsvNWD+E7xCRXlpbsiNJcObXl2rThoFaEeoa4YFkhoAGiCYbm08CJoFYlNKXWUPT/mTT8b9jcGzCd6jT1WmtjmeJWWiE7Us39W5lt3b391lduzw3+hs/RXl+SnVFQeEVf9mk4Ps9zED0JE6Cu2FpmPNMwI=",
      "SESSION_SECRET": "AgBMyqdNUcciiWYlLGn0Eyuyb4IwCVP2x3aL0AMIZnWS+ccOFaw0pBWF5hz9bRLkg71H0sS8iJnhDE6Z2cJoUmvvklnePA+M7BIiC9oED/qqbTpJcHbNi1CZSrLucm8HWMcd1v47TBadxS7LZ+rdYHCtTvEChRhaGotyRTa/LRR4nGHMDi0lk64nlh/1PdpNbrWqHUflyeDRpcEjcG18cnUR65Y1ngI5PiladKPKkrQp5Zir+lN2CnGMBFfBy+cHTbccl0y9aT0gXXF98jbxyGbnrx/eCN6y3lknEw/0GZZ63xzHir1Nb7hjvMkM+D62kZDoPRO5nnPyapLdDkcMcYEoOfpcLxnap4z1/GFtku5+Q8QZuRIaSsyIn+7a2zZCU/qBfkuwAHci+zRBOI6uof15SYwB4qkRGkLMdXscDxPBB5cFE5thKFOGAOZTFsCIJKX2d3+JnJ4xuOGXu6biF8Vt2wRsAXKBZBdRzUXgIL1xFGSKUZeNg/IJbnViTeMp+RLDxCvqRAOVTw62Y5bUcBMg4eUWpdC5kRj/9tq+D+62UDpUY8zvNfCMcoiJZnQ+JpX2fTTM91eaqDn0dKkKRXzT1+eQYZFCRHm4ogH2OWPa8N2XVYUMvSLb9vvVC79YcuVox5Lld+E4EmyJ/Ppi0+rTmATlh49qpYI7hm7yE0QveADYbnzksqBklXKB2OQJN6uhMcyrK6T3T7LvjbQ5XBEnpO2QZ3WECplLvP3T344Li4G/jeIYZPyUdTczb1VBNwk="
    },
    "name": "vars-r69"
  }
}
