{
  "containerPort": 4000,
  "deploymentStrategy": "ROLLING",
  "health": {
    "timeoutSeconds": 300
  },
  "hostAliases": [
    {
      "name": "mongo",
      "target": "app.svc-38.svc.cluster.local"
    }
  ],
  "image": {
    "digest": "sha256:0459a99b4fe17af90996a3e8d057e6774d1129e4151ee42495d0127b6b8948ff",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/39"
  },
  "iris": {
    "deploymentId": 173,
    "serviceName": "app",
    "targetName": "aws"
  },
  "projectId": "17",
  "release": {
    "id": 88,
    "sourceSha": "42568f377943e77ee01fdda30ed833d96f9defe9"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "app-39.likelion.uk"
  },
  "service": {
    "exposeContainerPort": true
  },
  "variables": {
    "encryptedData": {
      "MONGO_APP_PASSWORD": "AgAPuchPS2rFA2L9e0ZDvF8aBxSKfttitlXE2iJT+i05V5Pb/svNrBtljME8EXW55Ccm6iR6A4d6HhTJ5nICw0iI4fp0/jTgQzFNDCOV1jNpA9G4qzd2MQKMBFOR3eVNvSdWUf8oeIhwNIwJzouVdShHa8NYuJ3kXis8B0Cx08ur/fVpvoQ37tAAwhba/ILNAVspJgd0B+VXPPUU3gGRgS27fbXu94owHN5YuFep6JZXpS4aP8eAeiY+Eax5SS0Vp35HADpPbBHG/VlQfA+hE+5557JvNMvPCBjVw/838YRsXXFVrK4aF8QdiqscSZHAGXFxybf/XPQsThceyRWg4z3mI+qtWnBj7+Ri10BEkUY8oqB/3NMFQDEasbQXZYzK5agLy1xLhJpNdC2F6NG+NMqIb7+3SgUytY64qFrB/zJS5zhHq0ISszRAfIOTHIp1LxJz4NrlmNHvO5IL9MS9KzFzsK4YSh3RubW3i3R4M6vm2bI4L/dKETAE2t/mbNnziZ+UZHUIB4B648FLHi7yOIQihZg0nOqRUJcmLn8Cf3vq5xPAeE7mc884xykP8iDEle9zb/lfUtDYsQcKZsh0UkIGkBssrV98MNHz3Z54WqcoOXBQUD4wdBVq+GTMkL3gQ5i5CiDNAtSUTSkE8o5p6TvgzWWYKwXbdgDQfI//vyvQtdhCORWQR4VKcRKbSQDHo2yx2KnK",
      "MONGO_ROOT_PASSWORD": "AgBDE1mBK/56tmUlgzbjd951/Sz4cOknfTv8UzYZWASBkJfm0W7WAn26aUn/Fn8IYFpmicOgkKg4hNeHJkZL+6tqhmCgenamgVW3pMn9tXwneX5zxqn1P/softfQFJO37ANerB+9RNEkfdMV3NspeT88rVKElpTDmU/ZTP2Tsf/y980jfirVtF6daDmkpgtcWs4yRHCp9b7BXNy/Z4QNxWyQcUN+ch9se074y+K71dMojuyCcCnSbYhx4Ytmyp7eTj3B0UiSVnhwrmsWOm5xaDXZU9FZJK138VqHpWjBDjFF8c9WYwk/E3gFEAgtJIEXu0UmdAkXbhuoloZQAcoeqJRa+rfHQ0JSGc1Y+XClUVhnAbausG9KRZ4p1D2Ncb66G81LethiBP7OBuH9p5IwwU5VsWWJwsKI2XChx3d1encAReoz1eqa8xoiRQar3HFKcRds/cKf/kleI51q364qGMq69ooFPDoe3oIWavXKv2VKacSl3mslNC6HrkDP8WNkI1e+n0tYtRto/i7KE6eJFL3QFcvElg/1zjBPtXTah8Putk7ZeI+7egdv0Ss1TJ4TmPI4S/fFThtNYH+QA9X+4sV/sFxmBr+GbNfRpFM9AV05P8RhRZjIZzS8fg+RfBQDrHrhVfBEYMW6MiGzzsm74orjszbnTUFjEgPFATS+F/EtsZEh4gl0Tx+eMibMHDzO1KcMxjGK",
      "MONGO_URI": "AgCiAAAp6rW0vyIOapoDjRcSBg4M+gD67d6GM/He9LiYbUP/KC4BTaXRFrIFQL1LEIf1pA3IGWuh+voKRQg+V1eSvsRCLouSQAHh4ouAx5qvRdnzcbyX5polsE90IIVuHCYT7zrPVhij8tMmdwz6ntfwd4moL761tavdhbvsm43sUNNba9J9ww+vUWP1d4ytQ1HiJ0a5HcAS/BisZtHJmN49tJxP8Cd73HBl/ZJOhVEU35St22n8JpwHwqTt+Gb8WnQX0F8shY5EEvXTTF/2LtQu+FYNpxHqjbx4W3m87ORdLRPOyIQ6xMAOseIEAQbn4gHTRYvBGbWD6uH8AkQZEyrnQsmO2Nk178uvyMyPHJJITGvTQKVgglxZGR9f9Lo4d61TQ/5+ndmPEDb8wcArnu1ua5ekhCHRe/yBENnLCjZXh7p0XQ75gkuWtxCNK3yQ8Ocyho1HmWeP8/4OVm6PW2A14GEPeyoPrcPyTIA9MxsE3g28S/kIWYKg2BhozRP1PC6k54bA6lT1wgiqVerkuzkulywIxPs2S1QU3JihHAeCuvlVSfWMGtP5AS2CrbwjDGkre3mKPTCggNt8/CqgFOs1uCA8+KJj8VS9XBl0AWlG5urmmkgYdCqKfavdbo3Dp77AYz9ReNMTOP7fOHqfm/8pbbgFjTug8ClBSg8BFb1Yk47aeZgvrMa6rjwKjZkwDgiaGm600ayFUL5PguVMHj9DikZIbnLXDjYZ6OODFhDEX5brsnKbP/ws9Hy0m8lEW9nYRLSxpqNwN65/FS9s9D81IJNp4IlbOTYKmPxBiBQc+f4AFosXELjB8lp+7XTd/kDeVBOKieiQhnoILxc=",
      "SESSION_SECRET": "AgAyUx02J/SK+gSseU9rsWsE7VTpajUkxgzK26sE/WKMAypXq8rvXi6yk7fL9cBIT4elbdF+EklxxEg7LFjBaKEtvfrcMROf6L4NKOkqu8S/O7a7kQoKf3iyZ2mI1uVZuDA+H+iNBarRNTVoB1AdyIpoBL/5q+If4HHfx3XkDnGOmANdCDeUfDMOCl66k8cvYod3KG2XmXLPSHzLLzWFUlJwHjJjo4vILgcj6Xb+sDiftB36GVu4u3g1EMuKQ8z6fCRtQsFKgG5nG5d7HhLA8azXduhAdO7gt08HSpHbycTyb6RJPQyKF+WdsrRz7ZQdgqh87rkHKn3ykHZtH2bdMBSZXfHOpQQ9hdk5kRCguO1Mm1WK4zWSlHOfSr/jUv7QzOkzdxBU6h/CK6aVO2i32hmw/Za9VY36SGpy7/Xv0LAsc4TPj1Z9sq+qWBdMsSRnwgHf/ALqGqNc6DRerB632GfNoxdA6XNuCejK7dUMNs7meKHet+pZD5yfQ5iQCUVaCzToZnLUJjZNY0sh2V8l5pAW+x4ib7e4bM9fGE6CNcvvlJh98zTJTqesmhoIl38KxJ0Q4mdhu0djJ4pkcQdq4m5mIc+wRggzS6nsgRLdZkiDWRfpw63WhQ/ZwxVoM0pe4NRs2T+Cfy9o4tMBkHM9AAGpe1aQvQV2MuQxK4zBDru/sMX/Nxy8s2Ht5Rk8erMqVUSLMLn9m2GIh6tyeuJ9ePnLhJklKNQAw32aXEl4vj7276fYzBMxsS/28iIHw+y5ikXpcljAggUK7ymlTCjG6ME5"
    },
    "name": "vars-r88"
  }
}
