{
  "containerPort": 8080,
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:c4e8c3e8698664bee45456d8cf5f87c5fce7c0fd8ca8854435934755585fd88e",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/8"
  },
  "iris": {
    "deploymentId": 21,
    "serviceName": "portpolio-production",
    "targetName": "aws"
  },
  "release": {
    "id": 18,
    "sourceSha": "f54230346fbfca4e34ae2cdd1a370217611d2191"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "portpolio-production-8.likelion.uk"
  }
}
