{
  "containerPort": 8080,
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:e29bbe48692b3993f7a744279fac5e32c5ed12b4c83e089c8f757ea755b6b1c0",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/9"
  },
  "iris": {
    "deploymentId": 22,
    "serviceName": "delete-e2e",
    "targetName": "aws"
  },
  "release": {
    "id": 19,
    "sourceSha": "446917d6b46febbe2b4f7927166a0cc501de667e"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "delete-e2e-9.likelion.uk"
  }
}
