{
  "containerPort": 8080,
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:470ff66b3bb9d489e0e68e9ed66277ed813737d995cde26c051464922368ee11",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/25"
  },
  "iris": {
    "deploymentId": 89,
    "serviceName": "public-autofix-demo",
    "targetName": "aws"
  },
  "release": {
    "id": 41,
    "sourceSha": "57c082be45600dcac3a2e1bc8ca7131118dbaf8a"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "public-autofix-demo-25.likelion.uk"
  }
}
