{
  "database": {
    "engine": "mongodb",
    "image": "docker.io/library/mongo:7@sha256:1f995ad6fdb93244a1addab1b58f934a0bc2f5643c38e02f5e9d7f0c7d227a7b",
    "port": 27017,
    "storage": "5Gi"
  },
  "iris": {
    "deploymentId": 168,
    "serviceName": "mongodb",
    "targetName": "aws"
  },
  "projectId": "29",
  "release": {
    "id": 85
  },
  "replicas": 1,
  "variables": {
    "encryptedData": {
      "MONGO_INITDB_DATABASE": "AgAfvdcb04mmKbH9cTeS2ZND7OnmTRvkkXhR8yd8AbJg5HQYdh0AGyrnBW0C0AQAS2vhiHuFAXr0O6/3+Wi4z+8aEwehew2dvGOYC1pbg2gsJ2it1c9b1NtgZe3voP9thU1h9Ye3sAAUqbOFs24OJXd6rkUIe2sYOMbv8AE/83xtbt60sX+dvC4iZ4t8Q6FipCfFsGQpACqNWLpfHQJP7UKkr0FO3Qb4XSTEPZ456f2wCL1Ak0nE78g2nRdiZpvD34KHO1zcqerMVcuEfsg5Gs/IMI93hRxeD2/xNUlxZUwt92Hip1f8+XB2JNeWT2rH1G/PWOIETWhYKWFC8SYISbYLbiUqhnmDk5YXTHXSTPNRuHZn/IgCout3Kf58P5JJVaHeq2BJVgRerUwrkWEXKLzOwNl15J5YLj0pRwNowwXsOImrbXlT6t2cZl8TtrZUdD9asc101XPMo9RzhUJ3p2r3lRNAk8d0GPpE1JXwmZTR0EPvkxaio7M8naZLqZyZabK0wNYZHcpkzFOCaUBlWnLer99Y9HqLvpHPtlRWSS4JJlO4oBJT69k1lp90iBufAMGF0aXpQYQpB1L2b5tNgcxzSY/D2GguhmsLngXXxD1OV+3XpR5lx3xiky2ymJx+cGa12pl7W2KgBoyctfy4QcRhThLbthmfX9fj57jQek6zpMMD5M6MnAT7os/vnctJhwuwmPY=",
      "MONGO_INITDB_ROOT_PASSWORD": "AgCuAX+TWsjd815IS1DlsDU46D5DFjp6Kguyi/uJ5AjEK9LYUEcoUH/gitlbz2HawBfvtIn96GEvxXD7FaQihoEIL00Rs7jvyFYU1rnRPR1v2cP/v8SmRHIACW01koCpqOT6kBNJvGXvQ938QDtOyLCZziPyaVTvMkz4izf3IZCuBtTlvsNXnOoGQPXzG2MJAubdWyAoi3gWHM1yH9ujbsT1EKRr0TnR297jOIgA1Fw/DqvbSVhjVGcOuMXET2mSETRXN3ssf6fkkJxpJ2J86U6jz+Vt3jyRf8bclEm3FlW/knNsEdC5gNGRUSFS7V6XQCtGyvbxVHXDKeiCzF+/5R+ZyGZuNOaYC2eHXyv+OWeIp9/mv9rLBoEnCjmCv4iHGrOH5QooxdYCdvKhcXIqaMkqcoB4GmCja8d37yNKoEjPJDJhh+4UZ/AIn33xgPfgbtTghtWThL4gY6j9BnbHFkHIJrGFUbbVoDULM72aeMm5qZgIKHj/cPxCjQDdKwUDW5Wcqj+GxQyhk94n6HusrooCZXoreQIoymtO7VF+NxHoE2fjetq3RZ6POdkXpBm24h3SYRxBjHRs1hu1en63kd6YOWXQ+EPAhsI63GgUYiPk1qMoQNGv3nyoaId8F2qo63Xk11DkgTrsTp2AgmGbPqEJgkC5+xOSxexT9TWxQ6e84wgRKW4EdcWdv8owEljxSI1VYApUa34I1+oket4I8dAILWohpFmSa8pJLObysO5I1g==",
      "MONGO_INITDB_ROOT_USERNAME": "AgCrygRFsDIYbc+F1ZiKdT1C5lLBPiWo4SBZ2M//qB7yPYPPYoqk0SQdyrIV+wKRzv6ULXDUaL5EaCm3ryXJ36Ki8hSrEOWLP8k8KcNvMAA9+moG5klHbkSFBeIcAMBab/Zw016UrFFnWsmdFwEgpi9HdCNUn9s/Rz54VzWz/4Vv2Rsw7g8ANDdhAIGvmiuhWW5d5yq3uHIyXv4B5oXYiX/yuzxlOcQHtx1Cm9JUX3f1Ko/efJA9XFAXP2Irh+BIrd4FjJ49Xrb4mkQxXH3Gn/dH91OCZH6j/juSZIsPkVmHjXxs3gtvt7iqQSWghKfBNiFEPOoA2nuusB00r0jmHRgzgww9gzZDMAG4Iv0I8+oNILrQKVyoNDiUMyypIuhre1hyi+DZZ4iYEaDADobxG6hXdtrelhTvdDmw3k73DdrQgvLyQmKyovM+VpKSJk25eUIcpinTBBoBMtmn7Pi1Q/AIlsBlh8ub+QKclV8SFTh8iF2tT/U1FhytYadXWlqCyhImmw6oCCbOzTB9O3Q+qPqrH/SZ7IwAktfuFcW0zg41UhneL5HNiQF05DSPoPXY1PcrPZIJtH5qjptZq1xJf29iJnynV3QqKEzHzju8DjUvv/hDbIwubzw07oLBHk6IUNiK2IZRK5rZKvp7tFauQ63bhxN+xf26didt427F47hOoZwVkSeWQH8l1OP+H+cCAaGkqn8="
    },
    "name": "vars-r85"
  },
  "workload": {
    "kind": "database"
  }
}
