{
  "containerPort": 8080,
  "health": {
    "timeoutSeconds": 300
  },
  "image": {
    "digest": "sha256:5098fc2b71818b7ee5ae6b4617f6c90cbebf91e5ba93444669009723cb085084",
    "repository": "187069338876.dkr.ecr.ap-northeast-2.amazonaws.com/iris/services/37"
  },
  "imagePullSecrets": [
    {
      "name": "iris-ecr-pull"
    }
  ],
  "iris": {
    "deploymentId": 131,
    "serviceName": "onprem-e2e-0148",
    "targetName": "onprem-ih39di8m"
  },
  "release": {
    "id": 67,
    "sourceSha": "446917d6b46febbe2b4f7927166a0cc501de667e"
  },
  "replicas": 1,
  "resources": {
    "limits": {
      "cpu": "1",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "100m",
      "memory": "256Mi"
    }
  },
  "route": {
    "host": "onprem-e2e-0148-37-ih39di8m.internal.likelion.uk"
  }
}
